/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * TgPoster.API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ScrapeChannelsCommand
} from '../tgPosterAPI.schemas';

import { customInstance } from '../../axios-instance';




/**
 * @summary Запуск скрейпинга каналов по URL-ам TGStat.
 */
export const postApiV1TgstatScrape = (
    scrapeChannelsCommand: ScrapeChannelsCommand,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/tgstat/scrape`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: scrapeChannelsCommand, signal
    },
      );
    }
  


export const getPostApiV1TgstatScrapeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TgstatScrape>>, TError,{data: ScrapeChannelsCommand}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1TgstatScrape>>, TError,{data: ScrapeChannelsCommand}, TContext> => {

const mutationKey = ['postApiV1TgstatScrape'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1TgstatScrape>>, {data: ScrapeChannelsCommand}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1TgstatScrape(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1TgstatScrapeMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1TgstatScrape>>>
    export type PostApiV1TgstatScrapeMutationBody = ScrapeChannelsCommand
    export type PostApiV1TgstatScrapeMutationError = unknown

    /**
 * @summary Запуск скрейпинга каналов по URL-ам TGStat.
 */
export const usePostApiV1TgstatScrape = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1TgstatScrape>>, TError,{data: ScrapeChannelsCommand}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1TgstatScrape>>,
        TError,
        {data: ScrapeChannelsCommand},
        TContext
      > => {

      const mutationOptions = getPostApiV1TgstatScrapeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    