/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * TgPoster.API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreatePromptSettingRequest,
  CreatePromptSettingResponse,
  EditPromptSettingRequest,
  GetApiV1PromptSettingParams,
  ProblemDetails,
  PromptSettingResponse,
  PromptSettingResponsePagedResponse
} from '../tgPosterAPI.schemas';

import { customInstance } from '../../axios-instance';




/**
 * @summary Создание промптов для расписания
 */
export const postApiV1PromptSetting = (
    createPromptSettingRequest: CreatePromptSettingRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CreatePromptSettingResponse>(
      {url: `/api/v1/prompt-setting`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPromptSettingRequest, signal
    },
      );
    }
  


export const getPostApiV1PromptSettingMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PromptSetting>>, TError,{data: CreatePromptSettingRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1PromptSetting>>, TError,{data: CreatePromptSettingRequest}, TContext> => {

const mutationKey = ['postApiV1PromptSetting'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1PromptSetting>>, {data: CreatePromptSettingRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1PromptSetting(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1PromptSettingMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1PromptSetting>>>
    export type PostApiV1PromptSettingMutationBody = CreatePromptSettingRequest
    export type PostApiV1PromptSettingMutationError = ProblemDetails

    /**
 * @summary Создание промптов для расписания
 */
export const usePostApiV1PromptSetting = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PromptSetting>>, TError,{data: CreatePromptSettingRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1PromptSetting>>,
        TError,
        {data: CreatePromptSettingRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1PromptSettingMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Получение списка промтов
 */
export const getApiV1PromptSetting = (
    params?: GetApiV1PromptSettingParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PromptSettingResponsePagedResponse>(
      {url: `/api/v1/prompt-setting`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiV1PromptSettingQueryKey = (params?: GetApiV1PromptSettingParams,) => {
    return [
    `/api/v1/prompt-setting`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV1PromptSettingQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1PromptSetting>>, TError = ProblemDetails>(params?: GetApiV1PromptSettingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PromptSetting>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1PromptSettingQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1PromptSetting>>> = ({ signal }) => getApiV1PromptSetting(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1PromptSetting>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1PromptSettingQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1PromptSetting>>>
export type GetApiV1PromptSettingQueryError = ProblemDetails


export function useGetApiV1PromptSetting<TData = Awaited<ReturnType<typeof getApiV1PromptSetting>>, TError = ProblemDetails>(
 params: undefined |  GetApiV1PromptSettingParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PromptSetting>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PromptSetting>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PromptSetting>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PromptSetting<TData = Awaited<ReturnType<typeof getApiV1PromptSetting>>, TError = ProblemDetails>(
 params?: GetApiV1PromptSettingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PromptSetting>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PromptSetting>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PromptSetting>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PromptSetting<TData = Awaited<ReturnType<typeof getApiV1PromptSetting>>, TError = ProblemDetails>(
 params?: GetApiV1PromptSettingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PromptSetting>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получение списка промтов
 */

export function useGetApiV1PromptSetting<TData = Awaited<ReturnType<typeof getApiV1PromptSetting>>, TError = ProblemDetails>(
 params?: GetApiV1PromptSettingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PromptSetting>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1PromptSettingQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Получение промпта по id
 */
export const getApiV1PromptSettingId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PromptSettingResponse>(
      {url: `/api/v1/prompt-setting/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1PromptSettingIdQueryKey = (id?: string,) => {
    return [
    `/api/v1/prompt-setting/${id}`
    ] as const;
    }

    
export const getGetApiV1PromptSettingIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1PromptSettingId>>, TError = ProblemDetails>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PromptSettingId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1PromptSettingIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1PromptSettingId>>> = ({ signal }) => getApiV1PromptSettingId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1PromptSettingId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1PromptSettingIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1PromptSettingId>>>
export type GetApiV1PromptSettingIdQueryError = ProblemDetails


export function useGetApiV1PromptSettingId<TData = Awaited<ReturnType<typeof getApiV1PromptSettingId>>, TError = ProblemDetails>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PromptSettingId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PromptSettingId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PromptSettingId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PromptSettingId<TData = Awaited<ReturnType<typeof getApiV1PromptSettingId>>, TError = ProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PromptSettingId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PromptSettingId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PromptSettingId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PromptSettingId<TData = Awaited<ReturnType<typeof getApiV1PromptSettingId>>, TError = ProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PromptSettingId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получение промпта по id
 */

export function useGetApiV1PromptSettingId<TData = Awaited<ReturnType<typeof getApiV1PromptSettingId>>, TError = ProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PromptSettingId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1PromptSettingIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Изменение промптов для расписания
 */
export const putApiV1PromptSettingId = (
    id: string,
    editPromptSettingRequest: EditPromptSettingRequest,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/prompt-setting/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: editPromptSettingRequest
    },
      );
    }
  


export const getPutApiV1PromptSettingIdMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1PromptSettingId>>, TError,{id: string;data: EditPromptSettingRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiV1PromptSettingId>>, TError,{id: string;data: EditPromptSettingRequest}, TContext> => {

const mutationKey = ['putApiV1PromptSettingId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1PromptSettingId>>, {id: string;data: EditPromptSettingRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV1PromptSettingId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV1PromptSettingIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1PromptSettingId>>>
    export type PutApiV1PromptSettingIdMutationBody = EditPromptSettingRequest
    export type PutApiV1PromptSettingIdMutationError = ProblemDetails

    /**
 * @summary Изменение промптов для расписания
 */
export const usePutApiV1PromptSettingId = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1PromptSettingId>>, TError,{id: string;data: EditPromptSettingRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV1PromptSettingId>>,
        TError,
        {id: string;data: EditPromptSettingRequest},
        TContext
      > => {

      const mutationOptions = getPutApiV1PromptSettingIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    