/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * TgPoster.API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiV1YoutubeCallbackParams,
  PostApiV1YoutubeBody
} from '../tgPosterAPI.schemas';

import { customInstance } from '../../axios-instance';




/**
 * @summary Регистрация Аккаунта, редиректит на гугл авторизацию
 */
export const postApiV1Youtube = (
    postApiV1YoutubeBody: PostApiV1YoutubeBody,
 signal?: AbortSignal
) => {
      
      const formData = new FormData();
if(postApiV1YoutubeBody.JsonFile !== undefined) {
 formData.append(`JsonFile`, postApiV1YoutubeBody.JsonFile)
 }
if(postApiV1YoutubeBody.ClientId !== undefined) {
 formData.append(`ClientId`, postApiV1YoutubeBody.ClientId)
 }
if(postApiV1YoutubeBody.ClientSecret !== undefined) {
 formData.append(`ClientSecret`, postApiV1YoutubeBody.ClientSecret)
 }

      return customInstance<void>(
      {url: `/api/v1/youtube`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData, signal
    },
      );
    }
  


export const getPostApiV1YoutubeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Youtube>>, TError,{data: PostApiV1YoutubeBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1Youtube>>, TError,{data: PostApiV1YoutubeBody}, TContext> => {

const mutationKey = ['postApiV1Youtube'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1Youtube>>, {data: PostApiV1YoutubeBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1Youtube(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1YoutubeMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1Youtube>>>
    export type PostApiV1YoutubeMutationBody = PostApiV1YoutubeBody
    export type PostApiV1YoutubeMutationError = unknown

    /**
 * @summary Регистрация Аккаунта, редиректит на гугл авторизацию
 */
export const usePostApiV1Youtube = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1Youtube>>, TError,{data: PostApiV1YoutubeBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1Youtube>>,
        TError,
        {data: PostApiV1YoutubeBody},
        TContext
      > => {

      const mutationOptions = getPostApiV1YoutubeMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Коллбэк от гугл обратно к нам
 */
export const getApiV1YoutubeCallback = (
    params?: GetApiV1YoutubeCallbackParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/youtube/callback`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetApiV1YoutubeCallbackQueryKey = (params?: GetApiV1YoutubeCallbackParams,) => {
    return [`/api/v1/youtube/callback`, ...(params ? [params]: [])] as const;
    }

    
export const getGetApiV1YoutubeCallbackQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1YoutubeCallback>>, TError = unknown>(params?: GetApiV1YoutubeCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1YoutubeCallback>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1YoutubeCallbackQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1YoutubeCallback>>> = ({ signal }) => getApiV1YoutubeCallback(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1YoutubeCallback>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1YoutubeCallbackQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1YoutubeCallback>>>
export type GetApiV1YoutubeCallbackQueryError = unknown


export function useGetApiV1YoutubeCallback<TData = Awaited<ReturnType<typeof getApiV1YoutubeCallback>>, TError = unknown>(
 params: undefined |  GetApiV1YoutubeCallbackParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1YoutubeCallback>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1YoutubeCallback>>,
          TError,
          Awaited<ReturnType<typeof getApiV1YoutubeCallback>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1YoutubeCallback<TData = Awaited<ReturnType<typeof getApiV1YoutubeCallback>>, TError = unknown>(
 params?: GetApiV1YoutubeCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1YoutubeCallback>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1YoutubeCallback>>,
          TError,
          Awaited<ReturnType<typeof getApiV1YoutubeCallback>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1YoutubeCallback<TData = Awaited<ReturnType<typeof getApiV1YoutubeCallback>>, TError = unknown>(
 params?: GetApiV1YoutubeCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1YoutubeCallback>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Коллбэк от гугл обратно к нам
 */

export function useGetApiV1YoutubeCallback<TData = Awaited<ReturnType<typeof getApiV1YoutubeCallback>>, TError = unknown>(
 params?: GetApiV1YoutubeCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1YoutubeCallback>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1YoutubeCallbackQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Отправка сообщения с видео в ютуб
 */
export const postApiV1YoutubeMessageId = (
    messageId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/youtube/${messageId}`, method: 'POST', signal
    },
      );
    }
  


export const getPostApiV1YoutubeMessageIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1YoutubeMessageId>>, TError,{messageId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1YoutubeMessageId>>, TError,{messageId: string}, TContext> => {

const mutationKey = ['postApiV1YoutubeMessageId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1YoutubeMessageId>>, {messageId: string}> = (props) => {
          const {messageId} = props ?? {};

          return  postApiV1YoutubeMessageId(messageId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1YoutubeMessageIdMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1YoutubeMessageId>>>
    
    export type PostApiV1YoutubeMessageIdMutationError = unknown

    /**
 * @summary Отправка сообщения с видео в ютуб
 */
export const usePostApiV1YoutubeMessageId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1YoutubeMessageId>>, TError,{messageId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1YoutubeMessageId>>,
        TError,
        {messageId: string},
        TContext
      > => {

      const mutationOptions = getPostApiV1YoutubeMessageIdMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    