networks:
  default:
    name: tg

services:
  tgposter-worker:
    volumes:
      - ./worker-logs:/app/logs
      - ./WTelegram.session:/app/WTelegram.session
    container_name: tgposter-worker
    image: ${TGPOSTER_WORKER_IMAGE:-ghcr.io/evilvegetarian/tgposter-worker:latest}
    ports:
      - '8090:8090'  
    user: "1654:1654"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:8090"
      DataBase__ConnectionString: ${CONNECTIONSTRING:-Host=localhost;Username=admin;Password=admin;Database=tg-db}
      TelegramSettings__api_id: ${TELEGRAM_API_ID}
      TelegramSettings__api_hash: ${TELEGRAM_API_HASH}
      TelegramSettings__phone_number: ${TELEGRAM_PHONE_NUMBER}
      TelegramOptions__SecretKey: ${TELEGRAMOPTIONS_SECRETKEY}
      