networks:
  default:
    name: tg

volumes:
  tg-pg:

services:
  postgres:
    container_name: tg-pg
    image: postgres:16.4
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'tg-db'
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - tg-pg:/var/lib/postgresql/data