/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * TgPoster.API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateCommentRepostRequest,
  CreateCommentRepostResponse,
  GetCommentRepostResponse,
  ListCommentRepostResponse,
  ProblemDetails,
  UpdateCommentRepostRequest
} from '../tgPosterAPI.schemas';

import { customInstance } from '../../axios-instance';




/**
 * @summary Создание настроек комментирующего репоста.
 */
export const postApiV1CommentRepost = (
    createCommentRepostRequest: CreateCommentRepostRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CreateCommentRepostResponse>(
      {url: `/api/v1/comment-repost`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCommentRepostRequest, signal
    },
      );
    }
  


export const getPostApiV1CommentRepostMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CommentRepost>>, TError,{data: CreateCommentRepostRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1CommentRepost>>, TError,{data: CreateCommentRepostRequest}, TContext> => {

const mutationKey = ['postApiV1CommentRepost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1CommentRepost>>, {data: CreateCommentRepostRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1CommentRepost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1CommentRepostMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1CommentRepost>>>
    export type PostApiV1CommentRepostMutationBody = CreateCommentRepostRequest
    export type PostApiV1CommentRepostMutationError = ProblemDetails

    /**
 * @summary Создание настроек комментирующего репоста.
 */
export const usePostApiV1CommentRepost = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CommentRepost>>, TError,{data: CreateCommentRepostRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1CommentRepost>>,
        TError,
        {data: CreateCommentRepostRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1CommentRepostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Получение списка настроек комментирующего репоста.
 */
export const getApiV1CommentRepost = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<ListCommentRepostResponse>(
      {url: `/api/v1/comment-repost`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1CommentRepostQueryKey = () => {
    return [
    `/api/v1/comment-repost`
    ] as const;
    }

    
export const getGetApiV1CommentRepostQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1CommentRepost>>, TError = ProblemDetails>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CommentRepost>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1CommentRepostQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1CommentRepost>>> = ({ signal }) => getApiV1CommentRepost(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1CommentRepost>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1CommentRepostQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1CommentRepost>>>
export type GetApiV1CommentRepostQueryError = ProblemDetails


export function useGetApiV1CommentRepost<TData = Awaited<ReturnType<typeof getApiV1CommentRepost>>, TError = ProblemDetails>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CommentRepost>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CommentRepost>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CommentRepost>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CommentRepost<TData = Awaited<ReturnType<typeof getApiV1CommentRepost>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CommentRepost>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CommentRepost>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CommentRepost>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CommentRepost<TData = Awaited<ReturnType<typeof getApiV1CommentRepost>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CommentRepost>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получение списка настроек комментирующего репоста.
 */

export function useGetApiV1CommentRepost<TData = Awaited<ReturnType<typeof getApiV1CommentRepost>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CommentRepost>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1CommentRepostQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Получение подробной информации о настройках комментирующего репоста.
 */
export const getApiV1CommentRepostId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<GetCommentRepostResponse>(
      {url: `/api/v1/comment-repost/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1CommentRepostIdQueryKey = (id?: string,) => {
    return [
    `/api/v1/comment-repost/${id}`
    ] as const;
    }

    
export const getGetApiV1CommentRepostIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1CommentRepostId>>, TError = ProblemDetails>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CommentRepostId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1CommentRepostIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1CommentRepostId>>> = ({ signal }) => getApiV1CommentRepostId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1CommentRepostId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1CommentRepostIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1CommentRepostId>>>
export type GetApiV1CommentRepostIdQueryError = ProblemDetails


export function useGetApiV1CommentRepostId<TData = Awaited<ReturnType<typeof getApiV1CommentRepostId>>, TError = ProblemDetails>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CommentRepostId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CommentRepostId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CommentRepostId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CommentRepostId<TData = Awaited<ReturnType<typeof getApiV1CommentRepostId>>, TError = ProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CommentRepostId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CommentRepostId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CommentRepostId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CommentRepostId<TData = Awaited<ReturnType<typeof getApiV1CommentRepostId>>, TError = ProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CommentRepostId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получение подробной информации о настройках комментирующего репоста.
 */

export function useGetApiV1CommentRepostId<TData = Awaited<ReturnType<typeof getApiV1CommentRepostId>>, TError = ProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CommentRepostId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1CommentRepostIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Обновление настроек комментирующего репоста (активен/неактивен).
 */
export const putApiV1CommentRepostId = (
    id: string,
    updateCommentRepostRequest: UpdateCommentRepostRequest,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/comment-repost/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateCommentRepostRequest
    },
      );
    }
  


export const getPutApiV1CommentRepostIdMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1CommentRepostId>>, TError,{id: string;data: UpdateCommentRepostRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiV1CommentRepostId>>, TError,{id: string;data: UpdateCommentRepostRequest}, TContext> => {

const mutationKey = ['putApiV1CommentRepostId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1CommentRepostId>>, {id: string;data: UpdateCommentRepostRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV1CommentRepostId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV1CommentRepostIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1CommentRepostId>>>
    export type PutApiV1CommentRepostIdMutationBody = UpdateCommentRepostRequest
    export type PutApiV1CommentRepostIdMutationError = ProblemDetails

    /**
 * @summary Обновление настроек комментирующего репоста (активен/неактивен).
 */
export const usePutApiV1CommentRepostId = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1CommentRepostId>>, TError,{id: string;data: UpdateCommentRepostRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV1CommentRepostId>>,
        TError,
        {id: string;data: UpdateCommentRepostRequest},
        TContext
      > => {

      const mutationOptions = getPutApiV1CommentRepostIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Удаление настроек комментирующего репоста.
 */
export const deleteApiV1CommentRepostId = (
    id: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/comment-repost/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiV1CommentRepostIdMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1CommentRepostId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1CommentRepostId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV1CommentRepostId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1CommentRepostId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV1CommentRepostId(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1CommentRepostIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1CommentRepostId>>>
    
    export type DeleteApiV1CommentRepostIdMutationError = ProblemDetails

    /**
 * @summary Удаление настроек комментирующего репоста.
 */
export const useDeleteApiV1CommentRepostId = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1CommentRepostId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1CommentRepostId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV1CommentRepostIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    