/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * TgPoster.API
 * OpenAPI spec version: 1.0
 */
export type AddDestinationOutcome = typeof AddDestinationOutcome[keyof typeof AddDestinationOutcome];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AddDestinationOutcome = {
  Added: 'Added',
  AlreadyAdded: 'AlreadyAdded',
  SourceChannel: 'SourceChannel',
  NoWritePermission: 'NoWritePermission',
  NoMediaPermission: 'NoMediaPermission',
  NotResolved: 'NotResolved',
  RateLimited: 'RateLimited',
  NotProcessed: 'NotProcessed',
  Pending: 'Pending',
} as const;

export interface AddDestinationResultDto {
  discoveredChannelId: string;
  /** @minLength 1 */
  title: string;
  outcome: AddDestinationOutcome;
  /** @nullable */
  destinationId?: string | null;
  /** @nullable */
  error?: string | null;
}

/**
 * Массовое добавление в репост всех каналов Discover, подходящих под фильтр
 */
export interface AddDestinationsFromDiscoverFilterRequest {
  /**
   * Фильтр по тематике (Category)
   * @nullable
   */
  category?: string | null;
  /**
   * Поиск по названию или username
   * @nullable
   */
  search?: string | null;
  /**
   * Тип: "channel" (канал) или "chat" (чат). null — без фильтра
   * @nullable
   */
  peerType?: string | null;
  /**
   * Минимальное число подписчиков (включительно)
   * @minimum 0
   * @maximum 2147483647
   * @nullable
   */
  minParticipants?: number | null;
  /**
   * Максимальное число подписчиков (включительно)
   * @minimum 0
   * @maximum 2147483647
   * @nullable
   */
  maxParticipants?: number | null;
  sortBy?: DiscoverSortBy;
  sortDirection?: SortDirection;
  /** Вступать в канал, если аккаунт ещё не участник. Без вступления репост в канал не работает */
  autoJoin?: boolean;
}

/**
 * Массовое добавление целевых каналов репоста из Discover
 */
export interface AddDestinationsFromDiscoverRequest {
  /**
   * Id обнаруженных каналов из Discover
   * @minItems 1
   * @maxItems 20
   */
  discoveredChannelIds: string[];
  /** Вступать в канал, если аккаунт ещё не участник. Без вступления репост в канал не работает */
  autoJoin?: boolean;
}

/**
 * Добавление целевого канала для репоста.
 */
export interface AddRepostDestinationRequest {
  /**
   * ID или @username целевого канала/чата/группы.
   * @minLength 0
   * @maxLength 255
   */
  chatIdentifier: string;
}

export interface AddRepostDestinationResponse {
  id: string;
  discoveredChannelId: string;
}

/**
 * Запрос на подтверждение сообщений
 */
export interface ApproveMessagesRequest {
  /** Список идентификаторов сообщений для подтверждения */
  messagesIds?: string[];
}

export type ChatStatus = typeof ChatStatus[keyof typeof ChatStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChatStatus = {
  Active: 'Active',
  Banned: 'Banned',
  Left: 'Left',
  Unknown: 'Unknown',
} as const;

export type ChatType = typeof ChatType[keyof typeof ChatType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChatType = {
  Channel: 'Channel',
  Group: 'Group',
  Unknown: 'Unknown',
} as const;

export interface ClassificationCategoryStat {
  name: string;
  count: number;
  /** @nullable */
  averageConfidence?: number | null;
}

export type ClassificationConfidenceBucket = typeof ClassificationConfidenceBucket[keyof typeof ClassificationConfidenceBucket];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClassificationConfidenceBucket = {
  Unknown: 'Unknown',
  UpTo50: 'UpTo50',
  From50To70: 'From50To70',
  From70To80: 'From70To80',
  From80To90: 'From80To90',
  Over90: 'Over90',
} as const;

export interface ClassificationConfidenceBucketCount {
  bucket: ClassificationConfidenceBucket;
  count: number;
}

export interface ClassificationHistoryItemResponse {
  id: string;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  avatarUrl?: string | null;
  /** @nullable */
  tgUrl?: string | null;
  /** @nullable */
  participantsCount?: number | null;
  /** @nullable */
  category?: string | null;
  /** @nullable */
  subcategory?: string | null;
  tags: string[];
  /** @nullable */
  language?: string | null;
  /** @nullable */
  confidence?: number | null;
  classifiedAt: string;
}

export interface ClassificationHistoryItemResponsePagedResponse {
  currentPage?: number;
  readonly totalPages?: number;
  pageSize?: number;
  totalCount?: number;
  readonly hasPreviousPage?: boolean;
  readonly hasNextPage?: boolean;
  data?: ClassificationHistoryItemResponse[];
}

export interface ClassificationStatsFreshness {
  classifiedLast24Hours: number;
  classifiedLast7Days: number;
  classifiedLast30Days: number;
  /** @nullable */
  lastClassifiedAt?: string | null;
}

export interface ClassificationStatsResponse {
  totals: ClassificationStatsTotals;
  freshness: ClassificationStatsFreshness;
  byCategory: ClassificationCategoryStat[];
  byLanguage: DiscoverNamedCount[];
  byConfidence: ClassificationConfidenceBucketCount[];
  topSubcategories: ClassificationSubcategoryStat[];
  topTags: DiscoverNamedCount[];
  classifiedByDay: DiscoverDailyCount[];
}

export interface ClassificationStatsTotals {
  total: number;
  eligible: number;
  skipped: number;
  classified: number;
  pending: number;
  withCategory: number;
  withTags: number;
  /** @nullable */
  averageConfidence?: number | null;
  distinctSubcategories: number;
  distinctTags: number;
}

export interface ClassificationSubcategoryStat {
  /** @nullable */
  category?: string | null;
  subcategory: string;
  count: number;
}

export interface CommentRepostItemDto {
  id: string;
  watchedChannel: string;
  scheduleId: string;
  scheduleName: string;
  isActive: boolean;
  /** @nullable */
  lastCheckDate?: string | null;
}

/**
 * Запрос на подключение аккаунта Bluesky
 */
export interface ConnectBlueskyRequest {
  /**
   * Handle аккаунта Bluesky
   * @minLength 3
   * @maxLength 253
   */
  handle: string;
  /**
   * App password Bluesky
   * @minLength 8
   * @maxLength 64
   */
  appPassword: string;
}

export interface ConnectSocialAccountResponse {
  id: string;
}

/**
 * Создание настроек комментирующего репоста.
 */
export interface CreateCommentRepostRequest {
  /** ID расписания (наш канал-источник). */
  scheduleId: string;
  /** ID Telegram сессии для мониторинга и отправки. */
  telegramSessionId: string;
  /**
   * Username или ссылка на отслеживаемый канал (@channel или t.me/channel).
   * @minLength 0
   * @maxLength 256
   */
  watchedChannel: string;
}

export interface CreateCommentRepostResponse {
  id: string;
}

/**
 * Запрос на создание связки расписания с аккаунтом соцсети
 */
export interface CreateCrossPostTargetRequest {
  /** Идентификатор аккаунта соцсети */
  socialAccountId: string;
  format: CrossPostFormat;
  linkTarget: CrossPostLinkTarget;
  /**
   * Произвольная ссылка, обязательна при своей ссылке
   * @minLength 0
   * @maxLength 512
   * @nullable
   */
  customLink?: string | null;
  /**
   * Варианты призыва построчно
   * @minLength 0
   * @maxLength 1000
   * @nullable
   */
  callToAction?: string | null;
  /** Прикладывать медиа к кросс-посту */
  includeMedia: boolean;
  /** Кросс-постить посты, созданные парсером чужих каналов */
  includeParsed: boolean;
  /**
   * Задержка публикации в минутах
   * @minimum 0
   * @maximum 1440
   */
  delayMinutes: number;
}

export interface CreateCrossPostTargetResponse {
  id: string;
}

/**
 * Запрос на создание дней недели с настройками публикации
 */
export interface CreateDaysRequest {
  /** Id расписания */
  scheduleId: string;
  /** Список дней недели с настройками публикации */
  daysOfWeek?: DayOfWeekRequest[];
}

export interface CreateMessageResponse {
  id: string;
}

/**
 * Request создания OpenRouter
 */
export interface CreateOpenRouterSettingRequest {
  /**
   * Модель в Open Router
   * @minLength 3
   */
  model: string;
  /**
   * Токен для авторизации Open Router
   * @minLength 5
   */
  token: string;
}

export interface CreateOpenRouterSettingResponse {
  id?: string;
}

/**
 * Создание запроса на парсинг канала
 */
export interface CreateParseChannelRequest {
  /** Канал который парсят. */
  channel: string;
  /** Раз в день будет проверять новые посты. */
  alwaysCheckNewPosts: boolean;
  /** Расписание для которого парсят канал. */
  scheduleId: string;
  /** Нужно ли удалять текст, и оставлять только картинку. */
  deleteText?: boolean;
  /** Нужно ли удалять медиа, и оставлять только текст. */
  deleteMedia?: boolean;
  /** Избегать постов с данными словами, предложениями, словосочетаниями. */
  avoidWords?: string[];
  /** Нужно ли подтверждать пост перед тем как его запостить в вашем канале.
Если не нужно, он будет автоматически поставлен в свободные даты {ScheduleId}.
Если расписание пусто, то нужно будет дополнительно подтверждать все равно. */
  needVerifiedPosts?: boolean;
  /**
   * Дата откуда парсить
   * @nullable
   */
  dateFrom?: string | null;
  /**
   * До какой даты парсить
   * @nullable
   */
  dateTo?: string | null;
  /** Нужно ли анализировать пост через аи */
  useAiForPosts?: boolean;
  /** Telegram сессия для парсинга канала (для доступа к приватным каналам). */
  telegramSessionId: string;
}

export interface CreateParseChannelResponse {
  id: string;
}

/**
 * Request создания промптов
 */
export interface CreatePromptSettingRequest {
  /** Id расписания для которого Промпты */
  scheduleId: string;
  /**
   * Промпт для текста
   * @nullable
   */
  textPrompt?: string | null;
  /**
   * Промпт для видео
   * @nullable
   */
  videoPrompt?: string | null;
  /**
   * Промпт для фото
   * @nullable
   */
  photoPrompt?: string | null;
}

export interface CreatePromptSettingResponse {
  id?: string;
}

/**
 * Запрос на создание прокси
 */
export interface CreateProxyRequest {
  /** Имя прокси для отображения */
  name?: string;
  type?: ProxyType;
  /** IP или доменное имя прокси */
  host?: string;
  /** Порт прокси */
  port?: number;
  /**
   * Имя пользователя (для SOCKS5/HTTP, опционально)
   * @nullable
   */
  username?: string | null;
  /**
   * Пароль (для SOCKS5/HTTP, опционально)
   * @nullable
   */
  password?: string | null;
  /**
   * Секрет для MTProxy (hex/base64)
   * @nullable
   */
  secret?: string | null;
}

export interface CreateProxyResponse {
  id?: string;
}

/**
 * Создание настроек репоста для расписания.
 */
export interface CreateRepostSettingsRequest {
  /** ID расписания, для которого создаются настройки репоста. */
  scheduleId: string;
  /** ID Telegram сессии для выполнения репостов. */
  telegramSessionId: string;
  /** Список целевых каналов/чатов для репоста (ID или @username). */
  destinations?: string[];
}

export interface CreateRepostSettingsResponse {
  id: string;
}

/**
 * Запрос на создание расписания
 */
export interface CreateScheduleRequest {
  /**
   * Название расписания
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /**
   * Название канала для публикации
   * @minLength 1
   * @maxLength 100
   */
  channel: string;
  /** Идентификатор Telegram бота */
  telegramBotId: string;
  /**
   * Идентификатор YouTube аккаунта (опционально)
   * @nullable
   */
  youTubeAccountId?: string | null;
}

export interface CreateScheduleResponse {
  id: string;
}

/**
 * Запрос на создание Telegram бота
 */
export interface CreateTelegramBotRequest {
  /** Токен телеграм бота */
  token: string;
}

export interface CreateTelegramBotResponse {
  id: string;
}

/**
 * Запрос на создание Telegram сессии
 */
export interface CreateTelegramSessionRequest {
  /** API ID приложения Telegram */
  apiId?: string;
  /** API Hash приложения Telegram */
  apiHash?: string;
  /** Номер телефона */
  phoneNumber?: string;
  /**
   * Название сессии (опционально)
   * @nullable
   */
  name?: string | null;
  /**
   * ID прокси для маршрутизации трафика сессии (опционально)
   * @nullable
   */
  proxyId?: string | null;
  /**
   * ID бота, который оповещает о проблемах с аккаунтом (опционально)
   * @nullable
   */
  notificationBotId?: string | null;
}

export interface CreateTelegramSessionResponse {
  id?: string;
  name?: string;
  isActive?: boolean;
  authStatus?: string;
}

export type CrossPostFormat = typeof CrossPostFormat[keyof typeof CrossPostFormat];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CrossPostFormat = {
  Teaser: 'Teaser',
  Full: 'Full',
  Announcement: 'Announcement',
} as const;

export type CrossPostLinkTarget = typeof CrossPostLinkTarget[keyof typeof CrossPostLinkTarget];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CrossPostLinkTarget = {
  Post: 'Post',
  Channel: 'Channel',
  Custom: 'Custom',
  None: 'None',
} as const;

export interface CrossPostPreviewPart {
  text: string;
  length: number;
  limit: number;
}

export interface CrossPostPreviewResponse {
  socialAccountId: string;
  platform: SocialPlatform;
  accountName: string;
  format: CrossPostFormat;
  parts: CrossPostPreviewPart[];
  warnings: string[];
}

export type CrossPostStatus = typeof CrossPostStatus[keyof typeof CrossPostStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CrossPostStatus = {
  Pending: 'Pending',
  InProgress: 'InProgress',
  Published: 'Published',
  Failed: 'Failed',
  Skipped: 'Skipped',
} as const;

export interface CrossPostStatusResponse {
  id: string;
  platform: SocialPlatform;
  accountName: string;
  status: CrossPostStatus;
  /** @nullable */
  externalUrl?: string | null;
  /** @nullable */
  error?: string | null;
  /** @nullable */
  publishedAt?: string | null;
}

export interface CrossPostTargetResponse {
  id: string;
  scheduleId: string;
  socialAccountId: string;
  platform: SocialPlatform;
  accountName: string;
  accountStatus: SocialAccountStatus;
  isActive: boolean;
  format: CrossPostFormat;
  linkTarget: CrossPostLinkTarget;
  /** @nullable */
  customLink?: string | null;
  /** @nullable */
  callToAction?: string | null;
  includeMedia: boolean;
  includeParsed: boolean;
  delayMinutes: number;
}

export interface DayListResponse {
  items: DayResponse[];
}

export type DayOfWeek = typeof DayOfWeek[keyof typeof DayOfWeek];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DayOfWeek = {
  Sunday: 'Sunday',
  Monday: 'Monday',
  Tuesday: 'Tuesday',
  Wednesday: 'Wednesday',
  Thursday: 'Thursday',
  Friday: 'Friday',
  Saturday: 'Saturday',
} as const;

export interface DayOfWeekListResponse {
  items: DayOfWeekResponse[];
}

/**
 * Настройки публикации для дня недели
 */
export interface DayOfWeekRequest {
  dayOfWeekPosting: DayOfWeek;
  /** Время начала */
  startPosting: string;
  /** Время окончания */
  endPosting: string;
  /**
   * Интервал в минутах между постами
   * @minimum 1
   * @maximum 1440
   */
  interval: number;
}

export interface DayOfWeekResponse {
  id?: number;
  name?: string;
}

export interface DayResponse {
  id: string;
  scheduleId: string;
  dayOfWeek: DayOfWeek;
  timePostings?: string[];
}

export interface DiscoverChannelResponse {
  id?: string;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  avatarUrl?: string | null;
  /** @nullable */
  participantsCount?: number | null;
  /** @nullable */
  peerType?: string | null;
  /** @nullable */
  tgUrl?: string | null;
  /** @nullable */
  category?: string | null;
  /** @nullable */
  subcategory?: string | null;
  /** @nullable */
  language?: string | null;
  /** @nullable */
  lastDiscoveredAt?: string | null;
}

export interface DiscoverChannelResponsePagedResponse {
  currentPage?: number;
  readonly totalPages?: number;
  pageSize?: number;
  totalCount?: number;
  readonly hasPreviousPage?: boolean;
  readonly hasNextPage?: boolean;
  data?: DiscoverChannelResponse[];
}

export type DiscoverChannelStatus = typeof DiscoverChannelStatus[keyof typeof DiscoverChannelStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DiscoverChannelStatus = {
  Pending: 'Pending',
  InProgress: 'InProgress',
  Completed: 'Completed',
  Error: 'Error',
  Skipped: 'Skipped',
} as const;

export interface DiscoverDailyCount {
  date: string;
  count: number;
}

export type DiscoverJobStatus = typeof DiscoverJobStatus[keyof typeof DiscoverJobStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DiscoverJobStatus = {
  Idle: 'Idle',
  Running: 'Running',
  CooldownWait: 'CooldownWait',
  Failed: 'Failed',
  Unknown: 'Unknown',
} as const;

export interface DiscoverNamedCount {
  name: string;
  count: number;
}

export interface DiscoverParseHistoryItemResponse {
  id: string;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  avatarUrl?: string | null;
  /** @nullable */
  tgUrl?: string | null;
  /** @nullable */
  peerType?: string | null;
  /** @nullable */
  category?: string | null;
  /** @nullable */
  participantsCount?: number | null;
  status: DiscoverChannelStatus;
  parsedAt: string;
  /** @nullable */
  foundAt?: string | null;
  /** @nullable */
  lastParsedMessageId?: number | null;
  foundCount: number;
  /** @nullable */
  sourceTitle?: string | null;
  /** @nullable */
  sourceUsername?: string | null;
}

export interface DiscoverParseHistoryItemResponsePagedResponse {
  currentPage?: number;
  readonly totalPages?: number;
  pageSize?: number;
  totalCount?: number;
  readonly hasPreviousPage?: boolean;
  readonly hasNextPage?: boolean;
  data?: DiscoverParseHistoryItemResponse[];
}

export type DiscoverParticipantsBucket = typeof DiscoverParticipantsBucket[keyof typeof DiscoverParticipantsBucket];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DiscoverParticipantsBucket = {
  Unknown: 'Unknown',
  UpTo1K: 'UpTo1K',
  From1KTo10K: 'From1KTo10K',
  From10KTo100K: 'From10KTo100K',
  Over100K: 'Over100K',
} as const;

export interface DiscoverParticipantsBucketCount {
  bucket: DiscoverParticipantsBucket;
  count: number;
}

/**
 * Поле для сортировки обнаруженных каналов
 */
export type DiscoverSortBy = typeof DiscoverSortBy[keyof typeof DiscoverSortBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DiscoverSortBy = {
  Participants: 'Participants',
  DiscoveredAt: 'DiscoveredAt',
  Title: 'Title',
} as const;

export interface DiscoverSourceStat {
  id: string;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  avatarUrl?: string | null;
  /** @nullable */
  tgUrl?: string | null;
  foundCount: number;
  /** @nullable */
  lastParsedAt?: string | null;
  isBanned: boolean;
}

export interface DiscoverStatsFreshness {
  parsedLast24Hours: number;
  parsedLast7Days: number;
  parsedLast30Days: number;
  foundLast24Hours: number;
  foundLast7Days: number;
  foundLast30Days: number;
  /** @nullable */
  firstFoundAt?: string | null;
  /** @nullable */
  lastFoundAt?: string | null;
  /** @nullable */
  lastParsedAt?: string | null;
}

export interface DiscoverStatsResponse {
  totals: DiscoverStatsTotals;
  freshness: DiscoverStatsFreshness;
  byStatus: DiscoverStatusCount[];
  byPeerType: DiscoverNamedCount[];
  byCategory: DiscoverNamedCount[];
  byLanguage: DiscoverNamedCount[];
  byParticipants: DiscoverParticipantsBucketCount[];
  parsedByDay: DiscoverDailyCount[];
  foundByDay: DiscoverDailyCount[];
  topSources: DiscoverSourceStat[];
}

export interface DiscoverStatsTotals {
  total: number;
  parsed: number;
  notParsed: number;
  public: number;
  private: number;
  classified: number;
  withParticipants: number;
  totalParticipants: number;
  banned: number;
}

export interface DiscoverStatusCount {
  status: DiscoverChannelStatus;
  count: number;
}

export interface DiscoverStatusResponse {
  status: DiscoverJobStatus;
  /** @nullable */
  lastStartedAt?: string | null;
  /** @nullable */
  lastFinishedAt?: string | null;
  /** @nullable */
  cooldownUntil?: string | null;
  /** @nullable */
  nextRunAt?: string | null;
  /** @nullable */
  lastError?: string | null;
  /** @nullable */
  progressCurrent?: number | null;
  /** @nullable */
  progressTotal?: number | null;
  /** @nullable */
  progressMessage?: string | null;
  /** @nullable */
  heartbeatAt?: string | null;
}

/**
 * Request создания промптов
 */
export interface EditPromptSettingRequest {
  /**
   * Промпт для текста
   * @nullable
   */
  textPrompt?: string | null;
  /**
   * Промпт для видео
   * @nullable
   */
  videoPrompt?: string | null;
  /**
   * Промпт для фото
   * @nullable
   */
  photoPrompt?: string | null;
}

export interface FileResponse {
  id: string;
  fileType?: FileTypes;
  /** @nullable */
  url?: string | null;
  /** @nullable */
  videoUrl?: string | null;
  /** @nullable */
  durationSeconds?: number | null;
  previewFiles?: PreviewFileResponse[];
}

export type FileTypes = typeof FileTypes[keyof typeof FileTypes];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FileTypes = {
  NoOne: 'NoOne',
  Image: 'Image',
  Video: 'Video',
} as const;

/**
 * Модель для представления значения Enum на фронтенде.
 */
export interface FileTypesEnumViewModel {
  value: FileTypes;
  /** Имя элемента Enum (для отображения пользователю). */
  name: string;
}

export interface GenerateAiContentResponse {
  content: string;
}

export interface GetCommentRepostResponse {
  id: string;
  watchedChannel: string;
  watchedChannelId: number;
  scheduleId: string;
  scheduleName: string;
  telegramSessionId: string;
  /** @nullable */
  telegramSessionName?: string | null;
  isActive: boolean;
  /** @nullable */
  lastProcessedPostId?: number | null;
  /** @nullable */
  lastCheckDate?: string | null;
  created: string;
}

export interface GetTimeResponse {
  postingTimes?: string[];
}

export interface ImportTelegramSessionResponse {
  id?: string;
  name?: string;
  isActive?: boolean;
  phoneNumber?: string;
}

export interface ListCommentRepostResponse {
  items: CommentRepostItemDto[];
}

export interface ListOpenRouterSettingResponse {
  openRouterSettingResponses: OpenRouterSettingResponse[];
}

export interface ListRepostSettingsResponse {
  items: RepostSettingsItemDto[];
}

export type MessageCrossPostFormat = typeof MessageCrossPostFormat[keyof typeof MessageCrossPostFormat];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessageCrossPostFormat = {
  Inherit: 'Inherit',
  Teaser: 'Teaser',
  Full: 'Full',
  Announcement: 'Announcement',
} as const;

export interface MessageResponse {
  id: string;
  /** @nullable */
  textMessage?: string | null;
  timePosting: string;
  scheduleId: string;
  needApprove: boolean;
  canApprove: boolean;
  files?: FileResponse[];
  isSent: boolean;
  hasVideo: boolean;
  hasYouTubeAccount: boolean;
  crossPostEnabled: boolean;
  crossPostFormat?: CrossPostFormat;
  crossPosts?: CrossPostStatusResponse[];
}

export interface MessageResponsePagedResponse {
  currentPage?: number;
  readonly totalPages?: number;
  pageSize?: number;
  totalCount?: number;
  readonly hasPreviousPage?: boolean;
  readonly hasNextPage?: boolean;
  data?: MessageResponse[];
}

/**
 * Поля для сортировки сообщений
 */
export type MessageSortBy = typeof MessageSortBy[keyof typeof MessageSortBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessageSortBy = {
  CreatedAt: 'CreatedAt',
  SentAt: 'SentAt',
} as const;

/**
 * Модель для представления значения Enum на фронтенде.
 */
export interface MessageSortByEnumViewModel {
  value: MessageSortBy;
  /** Имя элемента Enum (для отображения пользователю). */
  name: string;
}

/**
 * Статус сообщения
 */
export type MessageStatus = typeof MessageStatus[keyof typeof MessageStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessageStatus = {
  All: 'All',
  Planed: 'Planed',
  NotApproved: 'NotApproved',
  Delivered: 'Delivered',
  NotDelivered: 'NotDelivered',
} as const;

/**
 * Модель для представления значения Enum на фронтенде.
 */
export interface MessageStatusEnumViewModel {
  value: MessageStatus;
  /** Имя элемента Enum (для отображения пользователю). */
  name: string;
}

export interface OpenRouterSettingResponse {
  model: string;
  id: string;
}

export interface ParseChannelListResponse {
  items: ParseChannelResponse[];
}

export interface ParseChannelResponse {
  id: string;
  scheduleId: string;
  deleteText: boolean;
  deleteMedia: boolean;
  avoidWords: string[];
  needVerifiedPosts: boolean;
  /** @nullable */
  dateFrom?: string | null;
  /** @nullable */
  dateTo?: string | null;
  status: string;
  isActive: boolean;
  channel: string;
  /** @nullable */
  lastParseDate?: string | null;
  scheduleName: string;
  telegramSessionId: string;
  /** @nullable */
  telegramSessionName?: string | null;
  telegramSessionPhoneNumber: string;
  /** @nullable */
  totalMessagesCount?: number | null;
  parsedMessagesCount?: number;
}

/**
 * Запрос на предпросмотр кросс-поста
 */
export interface PreviewCrossPostRequest {
  /**
   * Идентификатор аккаунта соцсети, null — все связки расписания
   * @nullable
   */
  socialAccountId?: string | null;
  format?: CrossPostFormat;
  linkTarget?: CrossPostLinkTarget;
  /**
   * Переопределение своей ссылки
   * @minLength 0
   * @maxLength 512
   * @nullable
   */
  customLink?: string | null;
  /**
   * Переопределение вариантов призыва
   * @minLength 0
   * @maxLength 1000
   * @nullable
   */
  callToAction?: string | null;
  /**
   * Текст поста, null — текст последнего поста расписания с непустым текстом
   * @minLength 0
   * @maxLength 4096
   * @nullable
   */
  text?: string | null;
}

export interface PreviewFileResponse {
  url: string;
}

export interface ProblemDetails {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
  [key: string]: unknown;
}

export interface PromptSettingResponse {
  id: string;
  /** @nullable */
  videoPrompt?: string | null;
  /** @nullable */
  picturePrompt?: string | null;
  /** @nullable */
  textPrompt?: string | null;
}

export interface PromptSettingResponsePagedResponse {
  currentPage?: number;
  readonly totalPages?: number;
  pageSize?: number;
  totalCount?: number;
  readonly hasPreviousPage?: boolean;
  readonly hasNextPage?: boolean;
  data?: PromptSettingResponse[];
}

export interface ProxyListResponse {
  items: ProxyResponse[];
}

export interface ProxyResponse {
  id?: string;
  name?: string;
  type?: ProxyType;
  host?: string;
  port?: number;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  password?: string | null;
  /** @nullable */
  secret?: string | null;
  sessionsCount?: number;
  /** @nullable */
  created?: string | null;
}

export type ProxyType = typeof ProxyType[keyof typeof ProxyType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProxyType = {
  Socks5: 'Socks5',
  Http: 'Http',
  MTProxy: 'MTProxy',
} as const;

/**
 * Запрос на обновление токена доступа
 */
export interface RefreshTokenRequest {
  /** Токен обновления */
  refreshToken: string;
}

export interface RefreshTokenResponse {
  accessToken: string;
  refreshToken: string;
  refreshTokenExpiration: string;
}

export interface RepostDestinationDto {
  id: string;
  chatId: number;
  isActive: boolean;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  memberCount?: number | null;
  chatType?: ChatType;
  chatStatus?: ChatStatus;
  /** @nullable */
  avatarBase64?: string | null;
  /** @nullable */
  infoUpdatedAt?: string | null;
  /** @nullable */
  discoveredChannelId?: string | null;
  delayMinSeconds?: number;
  delayMaxSeconds?: number;
  repostEveryNth?: number;
  skipProbability?: number;
  /** @nullable */
  maxRepostsPerDay?: number | null;
}

export interface RepostImportJobResponse {
  jobId: string;
  status: RepostImportStatus;
  totalCount: number;
  addedCount: number;
  skippedCount: number;
  pendingCount: number;
  /** @nullable */
  retryAfterSeconds?: number | null;
  results: AddDestinationResultDto[];
}

export type RepostImportStatus = typeof RepostImportStatus[keyof typeof RepostImportStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RepostImportStatus = {
  Pending: 'Pending',
  InProgress: 'InProgress',
  CooldownWait: 'CooldownWait',
  Completed: 'Completed',
  Failed: 'Failed',
} as const;

export interface RepostLogDto {
  id: string;
  createdAt: string;
  repostSettingsId: string;
  scheduleName: string;
  sourceChannelName: string;
  messageId: string;
  /** @nullable */
  messagePreview?: string | null;
  messageTimePosting: string;
  destinationId: string;
  destinationChatId: number;
  /** @nullable */
  destinationTitle?: string | null;
  /** @nullable */
  destinationUsername?: string | null;
  status: RepostStatus;
  reason: RepostLogReason;
  /** @nullable */
  telegramMessageId?: number | null;
  /** @nullable */
  error?: string | null;
  /** @nullable */
  repostedAt?: string | null;
}

export interface RepostLogDtoPagedResponse {
  currentPage?: number;
  readonly totalPages?: number;
  pageSize?: number;
  totalCount?: number;
  readonly hasPreviousPage?: boolean;
  readonly hasNextPage?: boolean;
  data?: RepostLogDto[];
}

export type RepostLogReason = typeof RepostLogReason[keyof typeof RepostLogReason];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RepostLogReason = {
  None: 'None',
  EveryNth: 'EveryNth',
  SkipProbability: 'SkipProbability',
  DailyLimit: 'DailyLimit',
  MessageNotPublished: 'MessageNotPublished',
  DialogsUnavailable: 'DialogsUnavailable',
  SourceChannelNotResolved: 'SourceChannelNotResolved',
  DestinationNotAvailable: 'DestinationNotAvailable',
  Banned: 'Banned',
  ForwardFailed: 'ForwardFailed',
  TopicClosed: 'TopicClosed',
} as const;

export interface RepostLogReasonCount {
  reason: RepostLogReason;
  count: number;
}

export interface RepostLogsSummaryResponse {
  total: number;
  success: number;
  failed: number;
  skipped: number;
  /** @nullable */
  lastSuccessAt?: string | null;
  reasons: RepostLogReasonCount[];
}

export interface RepostSettingsItemDto {
  id: string;
  scheduleId: string;
  scheduleName: string;
  telegramSessionId: string;
  isActive: boolean;
  destinationsCount: number;
}

export interface RepostSettingsResponse {
  id: string;
  scheduleId: string;
  scheduleName: string;
  telegramSessionId: string;
  /** @nullable */
  telegramSessionName: string | null;
  isActive: boolean;
  defaultDelayMinSeconds: number;
  defaultDelayMaxSeconds: number;
  defaultRepostEveryNth: number;
  defaultSkipProbability: number;
  /** @nullable */
  defaultMaxRepostsPerDay: number | null;
  created: string;
  destinations: RepostDestinationDto[];
}

export type RepostStatus = typeof RepostStatus[keyof typeof RepostStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RepostStatus = {
  Pending: 'Pending',
  Success: 'Success',
  Failed: 'Failed',
  Skipped: 'Skipped',
} as const;

export interface ScheduleListResponse {
  items: ScheduleResponse[];
}

export interface ScheduleResponse {
  id: string;
  name: string;
  isActive: boolean;
  channelName: string;
  botName: string;
  telegramBotId: string;
  /** @nullable */
  openRouterId?: string | null;
  /** @nullable */
  promptId?: string | null;
  /** @nullable */
  youTubeAccountId?: string | null;
  postCount: number;
  pendingPostCount: number;
  /** @nullable */
  lastPostDate?: string | null;
  /** @nullable */
  signatureFooter?: string | null;
  signatureEnabled: boolean;
}

export interface ScrapeChannelsCommand {
  urls?: string[];
}

/**
 * Запрос на отправку пароля
 */
export interface SendPasswordRequest {
  /** Пароль */
  password?: string;
}

export interface SendPasswordResponse {
  success?: boolean;
  message?: string;
}

/**
 * Регистрация
 */
export interface SignInRequest {
  /**
   * Логин пользователя
   * @minLength 5
   * @maxLength 30
   */
  login: string;
  /**
   * Пароль пользователя
   * @minLength 5
   */
  password: string;
}

export interface SignInResponse {
  refreshToken: string;
  refreshTokenExpiration: string;
  accessToken: string;
}

/**
 * Логин
 */
export interface SignOnRequest {
  /**
   * Логин пользователя
   * @minLength 5
   * @maxLength 30
   */
  login: string;
  /**
   * Пароль пользователя
   * @minLength 5
   */
  password: string;
}

export interface SignOnResponse {
  userId: string;
}

export interface SocialAccountResponse {
  id: string;
  platform: SocialPlatform;
  name: string;
  status: SocialAccountStatus;
  /** @nullable */
  tokenExpiresAt?: string | null;
  /** @nullable */
  lastError?: string | null;
  created: string;
}

export type SocialAccountStatus = typeof SocialAccountStatus[keyof typeof SocialAccountStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SocialAccountStatus = {
  Active: 'Active',
  NeedsReauth: 'NeedsReauth',
} as const;

export type SocialPlatform = typeof SocialPlatform[keyof typeof SocialPlatform];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SocialPlatform = {
  Bluesky: 'Bluesky',
} as const;

/**
 * Направление сортировки
 */
export type SortDirection = typeof SortDirection[keyof typeof SortDirection];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SortDirection = {
  Asc: 'Asc',
  Desc: 'Desc',
} as const;

/**
 * Модель для представления значения Enum на фронтенде.
 */
export interface SortDirectionEnumViewModel {
  value: SortDirection;
  /** Имя элемента Enum (для отображения пользователю). */
  name: string;
}

export interface StartAuthResponse {
  status?: string;
  message?: string;
}

export interface TelegramBotListResponse {
  items: TelegramBotResponse[];
}

export interface TelegramBotResponse {
  id: string;
  name: string;
}

export interface TelegramSessionListResponse {
  items: TelegramSessionResponse[];
}

export interface TelegramSessionResponse {
  id?: string;
  phoneNumber?: string;
  /** @nullable */
  name?: string | null;
  isActive?: boolean;
  status?: TelegramSessionStatus;
  /** @nullable */
  created?: string | null;
  /** @nullable */
  proxyId?: string | null;
  /** @nullable */
  proxyName?: string | null;
  /** @nullable */
  notificationBotId?: string | null;
  /** @nullable */
  notificationBotName?: string | null;
}

export type TelegramSessionStatus = typeof TelegramSessionStatus[keyof typeof TelegramSessionStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TelegramSessionStatus = {
  AwaitingCode: 'AwaitingCode',
  CodeSent: 'CodeSent',
  AwaitingPassword: 'AwaitingPassword',
  Authorized: 'Authorized',
  Failed: 'Failed',
} as const;

/**
 * Обновление настроек комментирующего репоста.
 */
export interface UpdateCommentRepostRequest {
  /** Активны ли настройки. */
  isActive: boolean;
}

/**
 * Запрос на обновление связки расписания с аккаунтом соцсети
 */
export interface UpdateCrossPostTargetRequest {
  /** Активна ли связка */
  isActive: boolean;
  format: CrossPostFormat;
  linkTarget: CrossPostLinkTarget;
  /**
   * Произвольная ссылка, обязательна при своей ссылке
   * @minLength 0
   * @maxLength 512
   * @nullable
   */
  customLink?: string | null;
  /**
   * Варианты призыва построчно
   * @minLength 0
   * @maxLength 1000
   * @nullable
   */
  callToAction?: string | null;
  /** Прикладывать медиа к кросс-посту */
  includeMedia: boolean;
  /** Кросс-постить посты, созданные парсером чужих каналов */
  includeParsed: boolean;
  /**
   * Задержка публикации в минутах
   * @minimum 0
   * @maximum 1440
   */
  delayMinutes: number;
}

/**
 * Запрос на обновление настроек парсинга канала
 */
export interface UpdateParseChannelRequest {
  /** Канал который парсят. */
  channel: string;
  /** Раз в день будет проверять новые посты. */
  alwaysCheckNewPosts: boolean;
  /** Расписание для которого парсят канал. */
  scheduleId: string;
  /** Нужно ли удалять текст, и оставлять только картинку. */
  deleteText?: boolean;
  /** Нужно ли удалять медиа, и оставлять только текст. */
  deleteMedia?: boolean;
  /** Избегать постов с данными словами, предложениями, словосочетаниями. */
  avoidWords?: string[];
  /** Нужно ли подтверждать пост перед тем как его запостить в вашем канале.
Если не нужно, он будет автоматически поставлен в свободные даты {ScheduleId}.
Если расписание пусто, то нужно будет дополнительно подтверждать все равно. */
  needVerifiedPosts?: boolean;
  /**
   * Дата откуда парсить
   * @nullable
   */
  dateFrom?: string | null;
  /**
   * До какой даты парсить
   * @nullable
   */
  dateTo?: string | null;
  /** Использовать аи для постов */
  useAiForPosts?: boolean;
  /** Telegram сессия для парсинга канала (для доступа к приватным каналам). */
  telegramSessionId: string;
}

/**
 * Запрос на обновление прокси
 */
export interface UpdateProxyRequest {
  name?: string;
  type?: ProxyType;
  host?: string;
  port?: number;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  password?: string | null;
  /** @nullable */
  secret?: string | null;
}

/**
 * Обновление целевого канала репоста.
 */
export interface UpdateRepostDestinationRequest {
  /** Активен ли целевой канал. */
  isActive: boolean;
  /**
   * Минимальная задержка перед репостом (секунды).
   * @minimum 0
   * @maximum 2147483647
   */
  delayMinSeconds?: number;
  /**
   * Максимальная задержка перед репостом (секунды).
   * @minimum 0
   * @maximum 2147483647
   */
  delayMaxSeconds?: number;
  /**
   * Репостить каждое N-е сообщение (1 = каждое).
   * @minimum 1
   * @maximum 2147483647
   */
  repostEveryNth?: number;
  /**
   * Вероятность пропуска репоста (0-100%).
   * @minimum 0
   * @maximum 100
   */
  skipProbability?: number;
  /**
   * Максимальное количество репостов в день (null = без лимита).
   * @minimum 1
   * @maximum 2147483647
   * @nullable
   */
  maxRepostsPerDay?: number | null;
}

/**
 * Обновление настроек репоста.
 */
export interface UpdateRepostSettingsRequest {
  /** Активность настроек репоста. */
  isActive: boolean;
  /**
   * Общая минимальная задержка перед репостом (секунды), копируется на новые каналы
   * @minimum 0
   * @maximum 2147483647
   */
  defaultDelayMinSeconds?: number;
  /**
   * Общая максимальная задержка перед репостом (секунды), копируется на новые каналы
   * @minimum 0
   * @maximum 2147483647
   */
  defaultDelayMaxSeconds?: number;
  /**
   * Общая настройка "репостить каждое N-е сообщение" (1 = каждое), копируется на новые каналы
   * @minimum 1
   * @maximum 2147483647
   */
  defaultRepostEveryNth?: number;
  /**
   * Общая вероятность пропуска репоста (0-100%), копируется на новые каналы
   * @minimum 0
   * @maximum 100
   */
  defaultSkipProbability?: number;
  /**
   * Общий лимит репостов в день (null = без лимита), копируется на новые каналы
   * @minimum 1
   * @maximum 2147483647
   * @nullable
   */
  defaultMaxRepostsPerDay?: number | null;
}

/**
 * Запрос на обновление расписания
 */
export interface UpdateScheduleRequest {
  /**
   * Название расписания (опционально)
   * @maxLength 100
   * @nullable
   */
  name?: string | null;
  /**
   * Идентификатор YouTube аккаунта (опционально)
   * @nullable
   */
  youTubeAccountId?: string | null;
  /**
   * Идентификатор Telegram бота (опционально)
   * @nullable
   */
  telegramBotId?: string | null;
  /**
   * Общая подпись, приклеиваемая снизу к каждому посту расписания.
Поддерживает HTML-разметку Telegram. Пустая строка очищает подпись, null оставляет её без изменений
   * @maxLength 1024
   * @nullable
   */
  signatureFooter?: string | null;
  /**
   * Признак того, что подпись добавляется к постам (опционально)
   * @nullable
   */
  signatureEnabled?: boolean | null;
}

/**
 * Запрос на обновление Telegram бота
 */
export interface UpdateTelegramBotRequest {
  /**
   * Название телеграм бота
   * @nullable
   */
  name?: string | null;
  /** Активность телеграм бота */
  isActive?: boolean;
}

/**
 * Запрос на обновление Telegram сессии
 */
export interface UpdateTelegramSessionRequest {
  /**
   * Новое название сессии (опционально)
   * @nullable
   */
  name?: string | null;
  /** Активна ли сессия */
  isActive?: boolean;
  /**
   * ID прокси (null = без прокси)
   * @nullable
   */
  proxyId?: string | null;
  /**
   * ID бота для оповещений о проблемах с аккаунтом (null = без оповещений)
   * @nullable
   */
  notificationBotId?: string | null;
}

/**
 * Запрос на обновление времени публикации
 */
export interface UpdateTimeRequest {
  /** Id расписания */
  scheduleId: string;
  dayOfWeek: DayOfWeek;
  /** Время постов */
  times?: string[];
}

/**
 * Запрос на верификацию кода подтверждения
 */
export interface VerifyCodeRequest {
  /** Код подтверждения */
  code?: string;
}

export interface VerifyCodeResponse {
  success?: boolean;
  requiresPassword?: boolean;
  /** @nullable */
  message?: string | null;
}

export interface YouTubeAccountListResponse {
  items: YouTubeAccountResponse[];
}

export interface YouTubeAccountResponse {
  id: string;
  name: string;
  /** @nullable */
  defaultTitle?: string | null;
  /** @nullable */
  defaultDescription?: string | null;
  /** @nullable */
  defaultTags?: string | null;
  autoPostingVideo?: boolean;
}

export interface YouTubeAuthUrlResponse {
  url: string;
}

export type GetApiV1DayParams = {
/**
 * Идентификатор расписания
 */
scheduleId: string;
};

export type GetApiV1DiscoverParams = {
/**
 * Фильтр по тематике (Category)
 */
Category?: string;
/**
 * Поиск по названию или username
 */
Search?: string;
/**
 * Тип: "channel" (канал) или "chat" (чат). null — без фильтра.
 */
PeerType?: string;
/**
 * Минимальное число подписчиков (включительно)
 * @minimum 0
 * @maximum 2147483647
 */
MinParticipants?: number;
/**
 * Максимальное число подписчиков (включительно)
 * @minimum 0
 * @maximum 2147483647
 */
MaxParticipants?: number;
/**
 * Поле сортировки. По умолчанию — по числу подписчиков
 */
SortBy?: DiscoverSortBy;
/**
 * Направление сортировки. По умолчанию — по убыванию
 */
SortDirection?: SortDirection;
/**
 * Номер страницы.
 */
PageNumber?: number;
/**
 * Размер страницы.
 */
PageSize?: number;
};

export type GetApiV1DiscoverStatsParams = {
/**
 * Глубина таймлайнов «по дням» в днях, включая сегодня. По умолчанию — 30
 * @minimum 1
 * @maximum 365
 */
Days?: number;
};

export type GetApiV1DiscoverParseHistoryParams = {
/**
 * Поиск по названию или username
 */
Search?: string;
/**
 * Начало периода по времени парсинга (включительно)
 */
From?: string;
/**
 * Конец периода по времени парсинга (включительно)
 */
To?: string;
/**
 * Номер страницы.
 */
PageNumber?: number;
/**
 * Размер страницы.
 */
PageSize?: number;
};

export type GetApiV1DiscoverClassificationStatsParams = {
/**
 * Глубина таймлайнов «по дням» в днях, включая сегодня. По умолчанию — 30
 * @minimum 1
 * @maximum 365
 */
Days?: number;
};

export type GetApiV1DiscoverClassificationHistoryParams = {
/**
 * Поиск по названию или username
 */
Search?: string;
/**
 * Точное название тематики
 */
Category?: string;
/**
 * Корзина уверенности модели
 */
Confidence?: ClassificationConfidenceBucket;
/**
 * Начало периода по времени классификации (включительно)
 */
From?: string;
/**
 * Конец периода по времени классификации (включительно)
 */
To?: string;
/**
 * Номер страницы.
 */
PageNumber?: number;
/**
 * Размер страницы.
 */
PageSize?: number;
};

export type PostApiV1MessageBatchFromFilesBody = {
  /** Идентификатор расписания */
  ScheduleId: string;
  /** Список файлов для создания сообщений */
  Files: Blob[];
};

export type GetApiV1MessageParams = {
/**
 * ID расписания, к которому относятся сообщения. Обязательный параметр.
 */
ScheduleId: string;
/**
 * Фильтр по статусу сообщения.
 */
Status?: MessageStatus;
/**
 * Текстовый поиск по содержимому сообщения.
 */
SearchText?: string;
/**
 * Начальная дата создания для фильтрации (включительно).
 */
CreatedFrom?: string;
/**
 * Конечная дата создания для фильтрации (включительно).
 */
CreatedTo?: string;
/**
 * Поле для сортировки. По умолчанию - по дате создания.
 */
SortBy?: MessageSortBy;
/**
 * Направление сортировки. По умолчанию - по убыванию (сначала новые).
 */
SortDirection?: SortDirection;
/**
 * Номер страницы.
 */
PageNumber?: number;
/**
 * Размер страницы.
 */
PageSize?: number;
};

export type PostApiV1MessageBody = {
  /** Id расписания */
  ScheduleId: string;
  /** Время поста */
  TimePosting: string;
  /** Текстовое сообщение */
  TextMessage?: string;
  /** Файлы сообщения */
  Files?: Blob[];
  /** Кросс-постить ли пост в подключённые соцсети. По умолчанию — да */
  CrossPostEnabled?: boolean;
  CrossPostFormat?: MessageCrossPostFormat;
};

export type PutApiV1MessageIdBody = {
  /** Id расписания */
  ScheduleId: string;
  /** Время поста */
  TimePosting: string;
  /** Текстовое сообщение */
  TextMessage?: string;
  /** Старые файлы сообщения */
  OldFiles?: string[];
  /** Новые файлы сообщения */
  NewFiles?: Blob[];
  /** Кросс-постить ли пост; null — не менять */
  CrossPostEnabled?: boolean;
  CrossPostFormat?: MessageCrossPostFormat;
};

export type GetApiV1PromptSettingParams = {
/**
 * Номер страницы.
 */
PageNumber?: number;
/**
 * Размер страницы.
 */
PageSize?: number;
};

export type GetApiV1RepostLogsParams = {
/**
 * Показать только записи этих настроек репоста
 */
RepostSettingsId?: string;
/**
 * Показать только записи по конкретному целевому каналу
 */
DestinationId?: string;
/**
 * Показать только записи по конкретному сообщению
 */
MessageId?: string;
/**
 * Фильтр по статусу репоста
 */
Status?: RepostStatus;
/**
 * Начало периода (включительно)
 */
From?: string;
/**
 * Конец периода (включительно)
 */
To?: string;
/**
 * Номер страницы.
 */
PageNumber?: number;
/**
 * Размер страницы.
 */
PageSize?: number;
};

export type GetApiV1RepostLogsSummaryParams = {
/**
 * Считать только по этим настройкам репоста
 */
RepostSettingsId?: string;
/**
 * Считать только по конкретному целевому каналу
 */
DestinationId?: string;
/**
 * Считать только по конкретному сообщению
 */
MessageId?: string;
/**
 * Начало периода (включительно)
 */
From?: string;
/**
 * Конец периода (включительно)
 */
To?: string;
};

export type PostApiV1TelegramSessionImportBody = {
  /** API ID приложения Telegram */
  ApiId: string;
  /** API Hash приложения Telegram */
  ApiHash: string;
  /** Файл сессии WTelegram (.session) */
  SessionFile: Blob;
  /** Название сессии (опционально) */
  Name?: string;
  /** ID бота для оповещений о проблемах с аккаунтом (опционально) */
  NotificationBotId?: string;
};

export type PostApiV1YoutubeBody = {
  /** JSON файл с учетными данными */
  JsonFile?: Blob;
  /** Идентификатор клиента */
  ClientId?: string;
  /** Секретный ключ клиента */
  ClientSecret?: string;
};

export type GetApiV1YoutubeCallbackParams = {
/**
 * Код авторизации от Google
 */
code?: string;
/**
 * Идентификатор записи в базе данных
 */
state?: string;
/**
 * Сообщение об ошибке (если есть)
 */
error?: string;
};

