/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * TgPoster.API
 * OpenAPI spec version: 1.0
 */
/**
 * Добавление целевого канала для репоста.
 */
export interface AddRepostDestinationRequest {
  /**
   * ID или @username целевого канала/чата/группы.
   * @minLength 0
   * @maxLength 255
   */
  chatIdentifier: string;
}

export interface AddRepostDestinationResponse {
  id: string;
}

/**
 * Запрос на подтверждение сообщений
 */
export interface ApproveMessagesRequest {
  /** Список идентификаторов сообщений для подтверждения */
  messagesIds?: string[];
}

export type ChatStatus = typeof ChatStatus[keyof typeof ChatStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChatStatus = {
  Active: 'Active',
  Banned: 'Banned',
  Left: 'Left',
  Unknown: 'Unknown',
} as const;

export type ChatType = typeof ChatType[keyof typeof ChatType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChatType = {
  Channel: 'Channel',
  Group: 'Group',
  Unknown: 'Unknown',
} as const;

export interface CommentRepostItemDto {
  id: string;
  watchedChannel: string;
  scheduleId: string;
  scheduleName: string;
  isActive: boolean;
  /** @nullable */
  lastCheckDate?: string | null;
}

/**
 * Создание настроек комментирующего репоста.
 */
export interface CreateCommentRepostRequest {
  /** ID расписания (наш канал-источник). */
  scheduleId: string;
  /** ID Telegram сессии для мониторинга и отправки. */
  telegramSessionId: string;
  /**
   * Username или ссылка на отслеживаемый канал (@channel или t.me/channel).
   * @minLength 0
   * @maxLength 256
   */
  watchedChannel: string;
}

export interface CreateCommentRepostResponse {
  id: string;
}

/**
 * Запрос на создание дней недели с настройками публикации
 */
export interface CreateDaysRequest {
  /** Id расписания */
  scheduleId: string;
  /** Список дней недели с настройками публикации */
  daysOfWeek?: DayOfWeekRequest[];
}

export interface CreateMessageResponse {
  id: string;
}

/**
 * Request создания OpenRouter
 */
export interface CreateOpenRouterSettingRequest {
  /**
   * Модель в Open Router
   * @minLength 3
   */
  model: string;
  /**
   * Токен для авторизации Open Router
   * @minLength 5
   */
  token: string;
}

export interface CreateOpenRouterSettingResponse {
  id?: string;
}

/**
 * Создание запроса на парсинг канала
 */
export interface CreateParseChannelRequest {
  /** Канал который парсят. */
  channel: string;
  /** Раз в день будет проверять новые посты. */
  alwaysCheckNewPosts: boolean;
  /** Расписание для которого парсят канал. */
  scheduleId: string;
  /** Нужно ли удалять текст, и оставлять только картинку. */
  deleteText?: boolean;
  /** Нужно ли удалять медиа, и оставлять только текст. */
  deleteMedia?: boolean;
  /** Избегать постов с данными словами, предложениями, словосочетаниями. */
  avoidWords?: string[];
  /** Нужно ли подтверждать пост перед тем как его запостить в вашем канале.
Если не нужно, он будет автоматически поставлен в свободные даты {ScheduleId}.
Если расписание пусто, то нужно будет дополнительно подтверждать все равно. */
  needVerifiedPosts?: boolean;
  /**
   * Дата откуда парсить
   * @nullable
   */
  dateFrom?: string | null;
  /**
   * До какой даты парсить
   * @nullable
   */
  dateTo?: string | null;
  /** Нужно ли анализировать пост через аи */
  useAiForPosts?: boolean;
  /** Telegram сессия для парсинга канала (для доступа к приватным каналам). */
  telegramSessionId: string;
}

export interface CreateParseChannelResponse {
  id: string;
}

/**
 * Request создания промптов
 */
export interface CreatePromptSettingRequest {
  /** Id расписания для которого Промпты */
  scheduleId: string;
  /**
   * Промпт для текста
   * @nullable
   */
  textPrompt?: string | null;
  /**
   * Промпт для видео
   * @nullable
   */
  videoPrompt?: string | null;
  /**
   * Промпт для фото
   * @nullable
   */
  photoPrompt?: string | null;
}

export interface CreatePromptSettingResponse {
  id?: string;
}

/**
 * Создание настроек репоста для расписания.
 */
export interface CreateRepostSettingsRequest {
  /** ID расписания, для которого создаются настройки репоста. */
  scheduleId: string;
  /** ID Telegram сессии для выполнения репостов. */
  telegramSessionId: string;
  /** Список целевых каналов/чатов для репоста (ID или @username). */
  destinations?: string[];
}

export interface CreateRepostSettingsResponse {
  id: string;
}

/**
 * Запрос на создание расписания
 */
export interface CreateScheduleRequest {
  /**
   * Название расписания
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /**
   * Название канала для публикации
   * @minLength 1
   * @maxLength 100
   */
  channel: string;
  /** Идентификатор Telegram бота */
  telegramBotId: string;
  /**
   * Идентификатор YouTube аккаунта (опционально)
   * @nullable
   */
  youTubeAccountId?: string | null;
}

export interface CreateScheduleResponse {
  id: string;
}

/**
 * Запрос на создание Telegram бота
 */
export interface CreateTelegramBotRequest {
  /** Токен телеграм бота */
  token: string;
}

export interface CreateTelegramBotResponse {
  id: string;
}

/**
 * Запрос на создание Telegram сессии
 */
export interface CreateTelegramSessionRequest {
  /** API ID приложения Telegram */
  apiId?: string;
  /** API Hash приложения Telegram */
  apiHash?: string;
  /** Номер телефона */
  phoneNumber?: string;
  /**
   * Название сессии (опционально)
   * @nullable
   */
  name?: string | null;
}

export interface CreateTelegramSessionResponse {
  id?: string;
  name?: string;
  isActive?: boolean;
  authStatus?: string;
}

export interface DayListResponse {
  items: DayResponse[];
}

export type DayOfWeek = typeof DayOfWeek[keyof typeof DayOfWeek];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DayOfWeek = {
  Sunday: 'Sunday',
  Monday: 'Monday',
  Tuesday: 'Tuesday',
  Wednesday: 'Wednesday',
  Thursday: 'Thursday',
  Friday: 'Friday',
  Saturday: 'Saturday',
} as const;

export interface DayOfWeekListResponse {
  items: DayOfWeekResponse[];
}

/**
 * Настройки публикации для дня недели
 */
export interface DayOfWeekRequest {
  dayOfWeekPosting: DayOfWeek;
  /** Время начала */
  startPosting: string;
  /** Время окончания */
  endPosting: string;
  /**
   * Интервал в минутах между постами
   * @minimum 1
   * @maximum 1440
   */
  interval: number;
}

export interface DayOfWeekResponse {
  id?: number;
  name?: string;
}

export interface DayResponse {
  id: string;
  scheduleId: string;
  dayOfWeek: DayOfWeek;
  timePostings?: string[];
}

/**
 * Request создания промптов
 */
export interface EditPromptSettingRequest {
  /**
   * Промпт для текста
   * @nullable
   */
  textPrompt?: string | null;
  /**
   * Промпт для видео
   * @nullable
   */
  videoPrompt?: string | null;
  /**
   * Промпт для фото
   * @nullable
   */
  photoPrompt?: string | null;
}

export interface FileResponse {
  id: string;
  fileType?: FileTypes;
  /** @nullable */
  url?: string | null;
  /** @nullable */
  videoUrl?: string | null;
  /** @nullable */
  durationSeconds?: number | null;
  previewFiles?: PreviewFileResponse[];
}

export type FileTypes = typeof FileTypes[keyof typeof FileTypes];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FileTypes = {
  NoOne: 'NoOne',
  Image: 'Image',
  Video: 'Video',
} as const;

/**
 * Модель для представления значения Enum на фронтенде.
 */
export interface FileTypesEnumViewModel {
  value: FileTypes;
  /** Имя элемента Enum (для отображения пользователю). */
  name: string;
}

export interface GenerateAiContentResponse {
  content: string;
}

export interface GetCommentRepostResponse {
  id: string;
  watchedChannel: string;
  watchedChannelId: number;
  scheduleId: string;
  scheduleName: string;
  telegramSessionId: string;
  /** @nullable */
  telegramSessionName?: string | null;
  isActive: boolean;
  /** @nullable */
  lastProcessedPostId?: number | null;
  /** @nullable */
  lastCheckDate?: string | null;
  created: string;
}

export interface GetTimeResponse {
  postingTimes?: string[];
}

export interface ListCommentRepostResponse {
  items: CommentRepostItemDto[];
}

export interface ListOpenRouterSettingResponse {
  openRouterSettingResponses: OpenRouterSettingResponse[];
}

export interface ListRepostSettingsResponse {
  items: RepostSettingsItemDto[];
}

export interface MessageResponse {
  id: string;
  /** @nullable */
  textMessage?: string | null;
  timePosting: string;
  scheduleId: string;
  needApprove: boolean;
  canApprove: boolean;
  files?: FileResponse[];
  isSent: boolean;
  hasVideo: boolean;
  hasYouTubeAccount: boolean;
}

export interface MessageResponsePagedResponse {
  currentPage?: number;
  readonly totalPages?: number;
  pageSize?: number;
  totalCount?: number;
  readonly hasPreviousPage?: boolean;
  readonly hasNextPage?: boolean;
  data?: MessageResponse[];
}

/**
 * Поля для сортировки сообщений
 */
export type MessageSortBy = typeof MessageSortBy[keyof typeof MessageSortBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessageSortBy = {
  CreatedAt: 'CreatedAt',
  SentAt: 'SentAt',
} as const;

/**
 * Модель для представления значения Enum на фронтенде.
 */
export interface MessageSortByEnumViewModel {
  value: MessageSortBy;
  /** Имя элемента Enum (для отображения пользователю). */
  name: string;
}

/**
 * Статус сообщения
 */
export type MessageStatus = typeof MessageStatus[keyof typeof MessageStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessageStatus = {
  All: 'All',
  Planed: 'Planed',
  NotApproved: 'NotApproved',
  Delivered: 'Delivered',
  NotDelivered: 'NotDelivered',
} as const;

/**
 * Модель для представления значения Enum на фронтенде.
 */
export interface MessageStatusEnumViewModel {
  value: MessageStatus;
  /** Имя элемента Enum (для отображения пользователю). */
  name: string;
}

export interface OpenRouterSettingResponse {
  model: string;
  id: string;
}

export interface ParseChannelListResponse {
  items: ParseChannelResponse[];
}

export interface ParseChannelResponse {
  id: string;
  scheduleId: string;
  deleteText: boolean;
  deleteMedia: boolean;
  avoidWords: string[];
  needVerifiedPosts: boolean;
  /** @nullable */
  dateFrom?: string | null;
  /** @nullable */
  dateTo?: string | null;
  status: string;
  isActive: boolean;
  channel: string;
  /** @nullable */
  lastParseDate?: string | null;
  scheduleName: string;
  telegramSessionId: string;
  /** @nullable */
  totalMessagesCount?: number | null;
  parsedMessagesCount?: number;
}

export interface PreviewFileResponse {
  url: string;
}

export interface ProblemDetails {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
  [key: string]: unknown;
}

export interface PromptSettingResponse {
  id: string;
  /** @nullable */
  videoPrompt?: string | null;
  /** @nullable */
  picturePrompt?: string | null;
  /** @nullable */
  textPrompt?: string | null;
}

export interface PromptSettingResponsePagedResponse {
  currentPage?: number;
  readonly totalPages?: number;
  pageSize?: number;
  totalCount?: number;
  readonly hasPreviousPage?: boolean;
  readonly hasNextPage?: boolean;
  data?: PromptSettingResponse[];
}

/**
 * Запрос на обновление токена доступа
 */
export interface RefreshTokenRequest {
  /** Токен обновления */
  refreshToken: string;
}

export interface RefreshTokenResponse {
  accessToken: string;
  refreshToken: string;
  refreshTokenExpiration: string;
}

export interface RepostDestinationDto {
  id: string;
  chatId: number;
  isActive: boolean;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  memberCount?: number | null;
  chatType?: ChatType;
  chatStatus?: ChatStatus;
  /** @nullable */
  avatarBase64?: string | null;
  /** @nullable */
  infoUpdatedAt?: string | null;
  delayMinSeconds?: number;
  delayMaxSeconds?: number;
  repostEveryNth?: number;
  skipProbability?: number;
  /** @nullable */
  maxRepostsPerDay?: number | null;
}

export interface RepostSettingsItemDto {
  id: string;
  scheduleId: string;
  scheduleName: string;
  telegramSessionId: string;
  isActive: boolean;
  destinationsCount: number;
}

export interface RepostSettingsResponse {
  id: string;
  scheduleId: string;
  scheduleName: string;
  telegramSessionId: string;
  /** @nullable */
  telegramSessionName: string | null;
  isActive: boolean;
  created: string;
  destinations: RepostDestinationDto[];
}

export interface ScheduleListResponse {
  items: ScheduleResponse[];
}

export interface ScheduleResponse {
  id: string;
  name: string;
  isActive: boolean;
  channelName: string;
  botName: string;
  telegramBotId: string;
  /** @nullable */
  openRouterId?: string | null;
  /** @nullable */
  promptId?: string | null;
  /** @nullable */
  youTubeAccountId?: string | null;
}

/**
 * Запрос на отправку пароля
 */
export interface SendPasswordRequest {
  /** Пароль */
  password?: string;
}

export interface SendPasswordResponse {
  success?: boolean;
  message?: string;
}

/**
 * Регистрация
 */
export interface SignInRequest {
  /**
   * Логин пользователя
   * @minLength 5
   * @maxLength 30
   */
  login: string;
  /**
   * Пароль пользователя
   * @minLength 5
   */
  password: string;
}

export interface SignInResponse {
  refreshToken: string;
  refreshTokenExpiration: string;
  accessToken: string;
}

/**
 * Логин
 */
export interface SignOnRequest {
  /**
   * Логин пользователя
   * @minLength 5
   * @maxLength 30
   */
  login: string;
  /**
   * Пароль пользователя
   * @minLength 5
   */
  password: string;
}

export interface SignOnResponse {
  userId: string;
}

/**
 * Направление сортировки
 */
export type SortDirection = typeof SortDirection[keyof typeof SortDirection];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SortDirection = {
  Asc: 'Asc',
  Desc: 'Desc',
} as const;

/**
 * Модель для представления значения Enum на фронтенде.
 */
export interface SortDirectionEnumViewModel {
  value: SortDirection;
  /** Имя элемента Enum (для отображения пользователю). */
  name: string;
}

export interface StartAuthResponse {
  status?: string;
  message?: string;
}

export interface TelegramBotListResponse {
  items: TelegramBotResponse[];
}

export interface TelegramBotResponse {
  id: string;
  name: string;
}

export interface TelegramSessionListResponse {
  items: TelegramSessionResponse[];
}

export interface TelegramSessionResponse {
  id?: string;
  phoneNumber?: string;
  /** @nullable */
  name?: string | null;
  isActive?: boolean;
  status?: TelegramSessionStatus;
  /** @nullable */
  created?: string | null;
}

export type TelegramSessionStatus = typeof TelegramSessionStatus[keyof typeof TelegramSessionStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TelegramSessionStatus = {
  AwaitingCode: 'AwaitingCode',
  CodeSent: 'CodeSent',
  AwaitingPassword: 'AwaitingPassword',
  Authorized: 'Authorized',
  Failed: 'Failed',
} as const;

/**
 * Обновление настроек комментирующего репоста.
 */
export interface UpdateCommentRepostRequest {
  /** Активны ли настройки. */
  isActive: boolean;
}

/**
 * Запрос на обновление настроек парсинга канала
 */
export interface UpdateParseChannelRequest {
  /** Канал который парсят. */
  channel: string;
  /** Раз в день будет проверять новые посты. */
  alwaysCheckNewPosts: boolean;
  /** Расписание для которого парсят канал. */
  scheduleId: string;
  /** Нужно ли удалять текст, и оставлять только картинку. */
  deleteText?: boolean;
  /** Нужно ли удалять медиа, и оставлять только текст. */
  deleteMedia?: boolean;
  /** Избегать постов с данными словами, предложениями, словосочетаниями. */
  avoidWords?: string[];
  /** Нужно ли подтверждать пост перед тем как его запостить в вашем канале.
Если не нужно, он будет автоматически поставлен в свободные даты {ScheduleId}.
Если расписание пусто, то нужно будет дополнительно подтверждать все равно. */
  needVerifiedPosts?: boolean;
  /**
   * Дата откуда парсить
   * @nullable
   */
  dateFrom?: string | null;
  /**
   * До какой даты парсить
   * @nullable
   */
  dateTo?: string | null;
  /** Использовать аи для постов */
  useAiForPosts?: boolean;
  /** Telegram сессия для парсинга канала (для доступа к приватным каналам). */
  telegramSessionId: string;
}

/**
 * Обновление целевого канала репоста.
 */
export interface UpdateRepostDestinationRequest {
  /** Активен ли целевой канал. */
  isActive: boolean;
  /** Минимальная задержка перед репостом (секунды). */
  delayMinSeconds?: number;
  /** Максимальная задержка перед репостом (секунды). */
  delayMaxSeconds?: number;
  /** Репостить каждое N-е сообщение (1 = каждое). */
  repostEveryNth?: number;
  /** Вероятность пропуска репоста (0-100%). */
  skipProbability?: number;
  /**
   * Максимальное количество репостов в день (null = без лимита).
   * @nullable
   */
  maxRepostsPerDay?: number | null;
}

/**
 * Обновление настроек репоста.
 */
export interface UpdateRepostSettingsRequest {
  /** Активность настроек репоста. */
  isActive: boolean;
}

/**
 * Запрос на обновление расписания
 */
export interface UpdateScheduleRequest {
  /**
   * Название расписания (опционально)
   * @maxLength 100
   * @nullable
   */
  name?: string | null;
  /**
   * Идентификатор YouTube аккаунта (опционально)
   * @nullable
   */
  youTubeAccountId?: string | null;
  /**
   * Идентификатор Telegram бота (опционально)
   * @nullable
   */
  telegramBotId?: string | null;
}

/**
 * Запрос на обновление Telegram бота
 */
export interface UpdateTelegramBotRequest {
  /**
   * Название телеграм бота
   * @nullable
   */
  name?: string | null;
  /** Активность телеграм бота */
  isActive?: boolean;
}

/**
 * Запрос на обновление Telegram сессии
 */
export interface UpdateTelegramSessionRequest {
  /**
   * Новое название сессии (опционально)
   * @nullable
   */
  name?: string | null;
  /** Активна ли сессия */
  isActive?: boolean;
}

/**
 * Запрос на обновление времени публикации
 */
export interface UpdateTimeRequest {
  /** Id расписания */
  scheduleId: string;
  dayOfWeek: DayOfWeek;
  /** Время постов */
  times?: string[];
}

/**
 * Запрос на верификацию кода подтверждения
 */
export interface VerifyCodeRequest {
  /** Код подтверждения */
  code?: string;
}

export interface VerifyCodeResponse {
  success?: boolean;
  requiresPassword?: boolean;
  /** @nullable */
  message?: string | null;
}

export interface YouTubeAccountListResponse {
  items: YouTubeAccountResponse[];
}

export interface YouTubeAccountResponse {
  id: string;
  name: string;
  /** @nullable */
  defaultTitle?: string | null;
  /** @nullable */
  defaultDescription?: string | null;
  /** @nullable */
  defaultTags?: string | null;
  autoPostingVideo?: boolean;
}

export interface YouTubeAuthUrlResponse {
  url: string;
}

export type GetApiV1DayParams = {
/**
 * Идентификатор расписания
 */
scheduleId: string;
};

export type PostApiV1MessageBatchFromFilesBody = {
  /** Идентификатор расписания */
  ScheduleId: string;
  /** Список файлов для создания сообщений */
  Files: Blob[];
};

export type GetApiV1MessageParams = {
/**
 * ID расписания, к которому относятся сообщения. Обязательный параметр.
 */
ScheduleId: string;
/**
 * Фильтр по статусу сообщения.
 */
Status?: MessageStatus;
/**
 * Текстовый поиск по содержимому сообщения.
 */
SearchText?: string;
/**
 * Начальная дата создания для фильтрации (включительно).
 */
CreatedFrom?: string;
/**
 * Конечная дата создания для фильтрации (включительно).
 */
CreatedTo?: string;
/**
 * Поле для сортировки. По умолчанию - по дате создания.
 */
SortBy?: MessageSortBy;
/**
 * Направление сортировки. По умолчанию - по убыванию (сначала новые).
 */
SortDirection?: SortDirection;
/**
 * Номер страницы.
 */
PageNumber?: number;
/**
 * Размер страницы.
 */
PageSize?: number;
};

export type PostApiV1MessageBody = {
  /** Id расписания */
  ScheduleId: string;
  /** Время поста */
  TimePosting: string;
  /** Текстовое сообщение */
  TextMessage?: string;
  /** Файлы сообщения */
  Files?: Blob[];
};

export type PutApiV1MessageIdBody = {
  /** Id расписания */
  ScheduleId: string;
  /** Время поста */
  TimePosting: string;
  /** Текстовое сообщение */
  TextMessage?: string;
  /** Старые файлы сообщения */
  OldFiles?: string[];
  /** Новые файлы сообщения */
  NewFiles?: Blob[];
};

export type GetApiV1PromptSettingParams = {
/**
 * Номер страницы.
 */
PageNumber?: number;
/**
 * Размер страницы.
 */
PageSize?: number;
};

export type PostApiV1YoutubeBody = {
  /** JSON файл с учетными данными */
  JsonFile?: Blob;
  /** Идентификатор клиента */
  ClientId?: string;
  /** Секретный ключ клиента */
  ClientSecret?: string;
};

export type GetApiV1YoutubeCallbackParams = {
/**
 * Код авторизации от Google
 */
code?: string;
/**
 * Идентификатор записи в базе данных
 */
state?: string;
/**
 * Сообщение об ошибке (если есть)
 */
error?: string;
};

