/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * TgPoster.API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateOpenRouterSettingRequest,
  CreateOpenRouterSettingResponse,
  GetOpenRouterSettingResponse,
  ListOpenRouterSettingResponse,
  ProblemDetails
} from '../tgPosterAPI.schemas';

import { customInstance } from '../../axios-instance';




/**
 * @summary Создание настроек OpenRouter
 */
export const postApiV1OpenRouterSetting = (
    createOpenRouterSettingRequest: CreateOpenRouterSettingRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CreateOpenRouterSettingResponse>(
      {url: `/api/v1/open-router-setting`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createOpenRouterSettingRequest, signal
    },
      );
    }
  


export const getPostApiV1OpenRouterSettingMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1OpenRouterSetting>>, TError,{data: CreateOpenRouterSettingRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1OpenRouterSetting>>, TError,{data: CreateOpenRouterSettingRequest}, TContext> => {

const mutationKey = ['postApiV1OpenRouterSetting'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1OpenRouterSetting>>, {data: CreateOpenRouterSettingRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1OpenRouterSetting(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1OpenRouterSettingMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1OpenRouterSetting>>>
    export type PostApiV1OpenRouterSettingMutationBody = CreateOpenRouterSettingRequest
    export type PostApiV1OpenRouterSettingMutationError = ProblemDetails

    /**
 * @summary Создание настроек OpenRouter
 */
export const usePostApiV1OpenRouterSetting = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1OpenRouterSetting>>, TError,{data: CreateOpenRouterSettingRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1OpenRouterSetting>>,
        TError,
        {data: CreateOpenRouterSettingRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1OpenRouterSettingMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Получение списка настроек OpenRouter
 */
export const getApiV1OpenRouterSetting = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<ListOpenRouterSettingResponse>(
      {url: `/api/v1/open-router-setting`, method: 'GET', signal
    },
      );
    }
  

export const getGetApiV1OpenRouterSettingQueryKey = () => {
    return [`/api/v1/open-router-setting`] as const;
    }

    
export const getGetApiV1OpenRouterSettingQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1OpenRouterSetting>>, TError = ProblemDetails>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1OpenRouterSetting>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1OpenRouterSettingQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1OpenRouterSetting>>> = ({ signal }) => getApiV1OpenRouterSetting(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1OpenRouterSetting>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1OpenRouterSettingQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1OpenRouterSetting>>>
export type GetApiV1OpenRouterSettingQueryError = ProblemDetails


export function useGetApiV1OpenRouterSetting<TData = Awaited<ReturnType<typeof getApiV1OpenRouterSetting>>, TError = ProblemDetails>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1OpenRouterSetting>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1OpenRouterSetting>>,
          TError,
          Awaited<ReturnType<typeof getApiV1OpenRouterSetting>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1OpenRouterSetting<TData = Awaited<ReturnType<typeof getApiV1OpenRouterSetting>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1OpenRouterSetting>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1OpenRouterSetting>>,
          TError,
          Awaited<ReturnType<typeof getApiV1OpenRouterSetting>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1OpenRouterSetting<TData = Awaited<ReturnType<typeof getApiV1OpenRouterSetting>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1OpenRouterSetting>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получение списка настроек OpenRouter
 */

export function useGetApiV1OpenRouterSetting<TData = Awaited<ReturnType<typeof getApiV1OpenRouterSetting>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1OpenRouterSetting>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1OpenRouterSettingQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Получение настроек OpenRouter
 */
export const getApiV1OpenRouterSettingId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<GetOpenRouterSettingResponse>(
      {url: `/api/v1/open-router-setting/${id}`, method: 'GET', signal
    },
      );
    }
  

export const getGetApiV1OpenRouterSettingIdQueryKey = (id: string,) => {
    return [`/api/v1/open-router-setting/${id}`] as const;
    }

    
export const getGetApiV1OpenRouterSettingIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1OpenRouterSettingId>>, TError = ProblemDetails>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1OpenRouterSettingId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1OpenRouterSettingIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1OpenRouterSettingId>>> = ({ signal }) => getApiV1OpenRouterSettingId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1OpenRouterSettingId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1OpenRouterSettingIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1OpenRouterSettingId>>>
export type GetApiV1OpenRouterSettingIdQueryError = ProblemDetails


export function useGetApiV1OpenRouterSettingId<TData = Awaited<ReturnType<typeof getApiV1OpenRouterSettingId>>, TError = ProblemDetails>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1OpenRouterSettingId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1OpenRouterSettingId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1OpenRouterSettingId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1OpenRouterSettingId<TData = Awaited<ReturnType<typeof getApiV1OpenRouterSettingId>>, TError = ProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1OpenRouterSettingId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1OpenRouterSettingId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1OpenRouterSettingId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1OpenRouterSettingId<TData = Awaited<ReturnType<typeof getApiV1OpenRouterSettingId>>, TError = ProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1OpenRouterSettingId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получение настроек OpenRouter
 */

export function useGetApiV1OpenRouterSettingId<TData = Awaited<ReturnType<typeof getApiV1OpenRouterSettingId>>, TError = ProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1OpenRouterSettingId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1OpenRouterSettingIdQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Удаление настроек OpenRouter
 */
export const deleteApiV1OpenRouterSettingId = (
    id: string,
 ) => {
      
      
      return customInstance<ListOpenRouterSettingResponse>(
      {url: `/api/v1/open-router-setting/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiV1OpenRouterSettingIdMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1OpenRouterSettingId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1OpenRouterSettingId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV1OpenRouterSettingId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1OpenRouterSettingId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV1OpenRouterSettingId(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1OpenRouterSettingIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1OpenRouterSettingId>>>
    
    export type DeleteApiV1OpenRouterSettingIdMutationError = ProblemDetails

    /**
 * @summary Удаление настроек OpenRouter
 */
export const useDeleteApiV1OpenRouterSettingId = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1OpenRouterSettingId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1OpenRouterSettingId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV1OpenRouterSettingIdMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Добавление расписания к настройкам OpenRouter
 */
export const patchApiV1OpenRouterSettingIdScheduleScheduleId = (
    id: string,
    scheduleId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/open-router-setting/${id}/schedule/${scheduleId}`, method: 'PATCH'
    },
      );
    }
  


export const getPatchApiV1OpenRouterSettingIdScheduleScheduleIdMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1OpenRouterSettingIdScheduleScheduleId>>, TError,{id: string;scheduleId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1OpenRouterSettingIdScheduleScheduleId>>, TError,{id: string;scheduleId: string}, TContext> => {

const mutationKey = ['patchApiV1OpenRouterSettingIdScheduleScheduleId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1OpenRouterSettingIdScheduleScheduleId>>, {id: string;scheduleId: string}> = (props) => {
          const {id,scheduleId} = props ?? {};

          return  patchApiV1OpenRouterSettingIdScheduleScheduleId(id,scheduleId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1OpenRouterSettingIdScheduleScheduleIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1OpenRouterSettingIdScheduleScheduleId>>>
    
    export type PatchApiV1OpenRouterSettingIdScheduleScheduleIdMutationError = ProblemDetails

    /**
 * @summary Добавление расписания к настройкам OpenRouter
 */
export const usePatchApiV1OpenRouterSettingIdScheduleScheduleId = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1OpenRouterSettingIdScheduleScheduleId>>, TError,{id: string;scheduleId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1OpenRouterSettingIdScheduleScheduleId>>,
        TError,
        {id: string;scheduleId: string},
        TContext
      > => {

      const mutationOptions = getPatchApiV1OpenRouterSettingIdScheduleScheduleIdMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    