/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * TgPoster.API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateCrossPostTargetRequest,
  CreateCrossPostTargetResponse,
  CrossPostPreviewResponse,
  CrossPostTargetResponse,
  PreviewCrossPostRequest,
  ProblemDetails,
  UpdateCrossPostTargetRequest
} from '../tgPosterAPI.schemas';

import { customInstance } from '../../axios-instance';




/**
 * @summary Получение связок расписания
 */
export const getApiV1ScheduleScheduleIdCrossPostTargets = (
    scheduleId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CrossPostTargetResponse[]>(
      {url: `/api/v1/schedule/${scheduleId}/cross-post-targets`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1ScheduleScheduleIdCrossPostTargetsQueryKey = (scheduleId?: string,) => {
    return [
    `/api/v1/schedule/${scheduleId}/cross-post-targets`
    ] as const;
    }

    
export const getGetApiV1ScheduleScheduleIdCrossPostTargetsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1ScheduleScheduleIdCrossPostTargets>>, TError = ProblemDetails>(scheduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ScheduleScheduleIdCrossPostTargets>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1ScheduleScheduleIdCrossPostTargetsQueryKey(scheduleId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ScheduleScheduleIdCrossPostTargets>>> = ({ signal }) => getApiV1ScheduleScheduleIdCrossPostTargets(scheduleId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(scheduleId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1ScheduleScheduleIdCrossPostTargets>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1ScheduleScheduleIdCrossPostTargetsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ScheduleScheduleIdCrossPostTargets>>>
export type GetApiV1ScheduleScheduleIdCrossPostTargetsQueryError = ProblemDetails


export function useGetApiV1ScheduleScheduleIdCrossPostTargets<TData = Awaited<ReturnType<typeof getApiV1ScheduleScheduleIdCrossPostTargets>>, TError = ProblemDetails>(
 scheduleId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ScheduleScheduleIdCrossPostTargets>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ScheduleScheduleIdCrossPostTargets>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ScheduleScheduleIdCrossPostTargets>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ScheduleScheduleIdCrossPostTargets<TData = Awaited<ReturnType<typeof getApiV1ScheduleScheduleIdCrossPostTargets>>, TError = ProblemDetails>(
 scheduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ScheduleScheduleIdCrossPostTargets>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ScheduleScheduleIdCrossPostTargets>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ScheduleScheduleIdCrossPostTargets>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1ScheduleScheduleIdCrossPostTargets<TData = Awaited<ReturnType<typeof getApiV1ScheduleScheduleIdCrossPostTargets>>, TError = ProblemDetails>(
 scheduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ScheduleScheduleIdCrossPostTargets>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получение связок расписания
 */

export function useGetApiV1ScheduleScheduleIdCrossPostTargets<TData = Awaited<ReturnType<typeof getApiV1ScheduleScheduleIdCrossPostTargets>>, TError = ProblemDetails>(
 scheduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ScheduleScheduleIdCrossPostTargets>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1ScheduleScheduleIdCrossPostTargetsQueryOptions(scheduleId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Создание связки расписания с аккаунтом соцсети
 */
export const postApiV1ScheduleScheduleIdCrossPostTargets = (
    scheduleId: string,
    createCrossPostTargetRequest: CreateCrossPostTargetRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CreateCrossPostTargetResponse>(
      {url: `/api/v1/schedule/${scheduleId}/cross-post-targets`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCrossPostTargetRequest, signal
    },
      );
    }
  


export const getPostApiV1ScheduleScheduleIdCrossPostTargetsMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ScheduleScheduleIdCrossPostTargets>>, TError,{scheduleId: string;data: CreateCrossPostTargetRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1ScheduleScheduleIdCrossPostTargets>>, TError,{scheduleId: string;data: CreateCrossPostTargetRequest}, TContext> => {

const mutationKey = ['postApiV1ScheduleScheduleIdCrossPostTargets'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1ScheduleScheduleIdCrossPostTargets>>, {scheduleId: string;data: CreateCrossPostTargetRequest}> = (props) => {
          const {scheduleId,data} = props ?? {};

          return  postApiV1ScheduleScheduleIdCrossPostTargets(scheduleId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1ScheduleScheduleIdCrossPostTargetsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1ScheduleScheduleIdCrossPostTargets>>>
    export type PostApiV1ScheduleScheduleIdCrossPostTargetsMutationBody = CreateCrossPostTargetRequest
    export type PostApiV1ScheduleScheduleIdCrossPostTargetsMutationError = ProblemDetails

    /**
 * @summary Создание связки расписания с аккаунтом соцсети
 */
export const usePostApiV1ScheduleScheduleIdCrossPostTargets = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ScheduleScheduleIdCrossPostTargets>>, TError,{scheduleId: string;data: CreateCrossPostTargetRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1ScheduleScheduleIdCrossPostTargets>>,
        TError,
        {scheduleId: string;data: CreateCrossPostTargetRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1ScheduleScheduleIdCrossPostTargetsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Обновление связки расписания
 */
export const putApiV1ScheduleScheduleIdCrossPostTargetsId = (
    scheduleId: string,
    id: string,
    updateCrossPostTargetRequest: UpdateCrossPostTargetRequest,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/schedule/${scheduleId}/cross-post-targets/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateCrossPostTargetRequest
    },
      );
    }
  


export const getPutApiV1ScheduleScheduleIdCrossPostTargetsIdMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1ScheduleScheduleIdCrossPostTargetsId>>, TError,{scheduleId: string;id: string;data: UpdateCrossPostTargetRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiV1ScheduleScheduleIdCrossPostTargetsId>>, TError,{scheduleId: string;id: string;data: UpdateCrossPostTargetRequest}, TContext> => {

const mutationKey = ['putApiV1ScheduleScheduleIdCrossPostTargetsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1ScheduleScheduleIdCrossPostTargetsId>>, {scheduleId: string;id: string;data: UpdateCrossPostTargetRequest}> = (props) => {
          const {scheduleId,id,data} = props ?? {};

          return  putApiV1ScheduleScheduleIdCrossPostTargetsId(scheduleId,id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV1ScheduleScheduleIdCrossPostTargetsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1ScheduleScheduleIdCrossPostTargetsId>>>
    export type PutApiV1ScheduleScheduleIdCrossPostTargetsIdMutationBody = UpdateCrossPostTargetRequest
    export type PutApiV1ScheduleScheduleIdCrossPostTargetsIdMutationError = ProblemDetails

    /**
 * @summary Обновление связки расписания
 */
export const usePutApiV1ScheduleScheduleIdCrossPostTargetsId = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1ScheduleScheduleIdCrossPostTargetsId>>, TError,{scheduleId: string;id: string;data: UpdateCrossPostTargetRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV1ScheduleScheduleIdCrossPostTargetsId>>,
        TError,
        {scheduleId: string;id: string;data: UpdateCrossPostTargetRequest},
        TContext
      > => {

      const mutationOptions = getPutApiV1ScheduleScheduleIdCrossPostTargetsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Удаление связки расписания
 */
export const deleteApiV1ScheduleScheduleIdCrossPostTargetsId = (
    scheduleId: string,
    id: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/schedule/${scheduleId}/cross-post-targets/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiV1ScheduleScheduleIdCrossPostTargetsIdMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1ScheduleScheduleIdCrossPostTargetsId>>, TError,{scheduleId: string;id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1ScheduleScheduleIdCrossPostTargetsId>>, TError,{scheduleId: string;id: string}, TContext> => {

const mutationKey = ['deleteApiV1ScheduleScheduleIdCrossPostTargetsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1ScheduleScheduleIdCrossPostTargetsId>>, {scheduleId: string;id: string}> = (props) => {
          const {scheduleId,id} = props ?? {};

          return  deleteApiV1ScheduleScheduleIdCrossPostTargetsId(scheduleId,id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1ScheduleScheduleIdCrossPostTargetsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1ScheduleScheduleIdCrossPostTargetsId>>>
    
    export type DeleteApiV1ScheduleScheduleIdCrossPostTargetsIdMutationError = ProblemDetails

    /**
 * @summary Удаление связки расписания
 */
export const useDeleteApiV1ScheduleScheduleIdCrossPostTargetsId = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1ScheduleScheduleIdCrossPostTargetsId>>, TError,{scheduleId: string;id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1ScheduleScheduleIdCrossPostTargetsId>>,
        TError,
        {scheduleId: string;id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV1ScheduleScheduleIdCrossPostTargetsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Предпросмотр кросс-поста для связок расписания
 */
export const postApiV1ScheduleScheduleIdCrossPostTargetsPreview = (
    scheduleId: string,
    previewCrossPostRequest: PreviewCrossPostRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CrossPostPreviewResponse[]>(
      {url: `/api/v1/schedule/${scheduleId}/cross-post-targets/preview`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: previewCrossPostRequest, signal
    },
      );
    }
  


export const getPostApiV1ScheduleScheduleIdCrossPostTargetsPreviewMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ScheduleScheduleIdCrossPostTargetsPreview>>, TError,{scheduleId: string;data: PreviewCrossPostRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1ScheduleScheduleIdCrossPostTargetsPreview>>, TError,{scheduleId: string;data: PreviewCrossPostRequest}, TContext> => {

const mutationKey = ['postApiV1ScheduleScheduleIdCrossPostTargetsPreview'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1ScheduleScheduleIdCrossPostTargetsPreview>>, {scheduleId: string;data: PreviewCrossPostRequest}> = (props) => {
          const {scheduleId,data} = props ?? {};

          return  postApiV1ScheduleScheduleIdCrossPostTargetsPreview(scheduleId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1ScheduleScheduleIdCrossPostTargetsPreviewMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1ScheduleScheduleIdCrossPostTargetsPreview>>>
    export type PostApiV1ScheduleScheduleIdCrossPostTargetsPreviewMutationBody = PreviewCrossPostRequest
    export type PostApiV1ScheduleScheduleIdCrossPostTargetsPreviewMutationError = ProblemDetails

    /**
 * @summary Предпросмотр кросс-поста для связок расписания
 */
export const usePostApiV1ScheduleScheduleIdCrossPostTargetsPreview = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1ScheduleScheduleIdCrossPostTargetsPreview>>, TError,{scheduleId: string;data: PreviewCrossPostRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1ScheduleScheduleIdCrossPostTargetsPreview>>,
        TError,
        {scheduleId: string;data: PreviewCrossPostRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1ScheduleScheduleIdCrossPostTargetsPreviewMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    