/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * TgPoster.API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddRepostDestinationRequest,
  AddRepostDestinationResponse,
  CreateRepostSettingsRequest,
  CreateRepostSettingsResponse,
  ListRepostSettingsResponse,
  ProblemDetails,
  RepostSettingsResponse,
  UpdateRepostDestinationRequest,
  UpdateRepostSettingsRequest
} from '../tgPosterAPI.schemas';

import { customInstance } from '../../axios-instance';




/**
 * @summary Создание настроек репоста для расписания.
 */
export const postApiV1RepostSettings = (
    createRepostSettingsRequest: CreateRepostSettingsRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CreateRepostSettingsResponse>(
      {url: `/api/v1/repost/settings`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createRepostSettingsRequest, signal
    },
      );
    }
  


export const getPostApiV1RepostSettingsMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1RepostSettings>>, TError,{data: CreateRepostSettingsRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1RepostSettings>>, TError,{data: CreateRepostSettingsRequest}, TContext> => {

const mutationKey = ['postApiV1RepostSettings'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1RepostSettings>>, {data: CreateRepostSettingsRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1RepostSettings(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1RepostSettingsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1RepostSettings>>>
    export type PostApiV1RepostSettingsMutationBody = CreateRepostSettingsRequest
    export type PostApiV1RepostSettingsMutationError = ProblemDetails

    /**
 * @summary Создание настроек репоста для расписания.
 */
export const usePostApiV1RepostSettings = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1RepostSettings>>, TError,{data: CreateRepostSettingsRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1RepostSettings>>,
        TError,
        {data: CreateRepostSettingsRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1RepostSettingsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Получение списка всех настроек репоста пользователя.
 */
export const getApiV1RepostSettings = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<ListRepostSettingsResponse>(
      {url: `/api/v1/repost/settings`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1RepostSettingsQueryKey = () => {
    return [
    `/api/v1/repost/settings`
    ] as const;
    }

    
export const getGetApiV1RepostSettingsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1RepostSettings>>, TError = ProblemDetails>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1RepostSettings>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1RepostSettingsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1RepostSettings>>> = ({ signal }) => getApiV1RepostSettings(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1RepostSettings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1RepostSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1RepostSettings>>>
export type GetApiV1RepostSettingsQueryError = ProblemDetails


export function useGetApiV1RepostSettings<TData = Awaited<ReturnType<typeof getApiV1RepostSettings>>, TError = ProblemDetails>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1RepostSettings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1RepostSettings>>,
          TError,
          Awaited<ReturnType<typeof getApiV1RepostSettings>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1RepostSettings<TData = Awaited<ReturnType<typeof getApiV1RepostSettings>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1RepostSettings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1RepostSettings>>,
          TError,
          Awaited<ReturnType<typeof getApiV1RepostSettings>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1RepostSettings<TData = Awaited<ReturnType<typeof getApiV1RepostSettings>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1RepostSettings>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получение списка всех настроек репоста пользователя.
 */

export function useGetApiV1RepostSettings<TData = Awaited<ReturnType<typeof getApiV1RepostSettings>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1RepostSettings>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1RepostSettingsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Получение подробной информации о настройках репоста.
 */
export const getApiV1RepostSettingsId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<RepostSettingsResponse>(
      {url: `/api/v1/repost/settings/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1RepostSettingsIdQueryKey = (id?: string,) => {
    return [
    `/api/v1/repost/settings/${id}`
    ] as const;
    }

    
export const getGetApiV1RepostSettingsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1RepostSettingsId>>, TError = ProblemDetails>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1RepostSettingsId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1RepostSettingsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1RepostSettingsId>>> = ({ signal }) => getApiV1RepostSettingsId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1RepostSettingsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1RepostSettingsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1RepostSettingsId>>>
export type GetApiV1RepostSettingsIdQueryError = ProblemDetails


export function useGetApiV1RepostSettingsId<TData = Awaited<ReturnType<typeof getApiV1RepostSettingsId>>, TError = ProblemDetails>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1RepostSettingsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1RepostSettingsId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1RepostSettingsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1RepostSettingsId<TData = Awaited<ReturnType<typeof getApiV1RepostSettingsId>>, TError = ProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1RepostSettingsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1RepostSettingsId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1RepostSettingsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1RepostSettingsId<TData = Awaited<ReturnType<typeof getApiV1RepostSettingsId>>, TError = ProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1RepostSettingsId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получение подробной информации о настройках репоста.
 */

export function useGetApiV1RepostSettingsId<TData = Awaited<ReturnType<typeof getApiV1RepostSettingsId>>, TError = ProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1RepostSettingsId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1RepostSettingsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Удаление настроек репоста.
 */
export const deleteApiV1RepostSettingsId = (
    id: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/repost/settings/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiV1RepostSettingsIdMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1RepostSettingsId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1RepostSettingsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV1RepostSettingsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1RepostSettingsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV1RepostSettingsId(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1RepostSettingsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1RepostSettingsId>>>
    
    export type DeleteApiV1RepostSettingsIdMutationError = ProblemDetails

    /**
 * @summary Удаление настроек репоста.
 */
export const useDeleteApiV1RepostSettingsId = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1RepostSettingsId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1RepostSettingsId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV1RepostSettingsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Обновление настроек репоста (рандомность, активность).
 */
export const putApiV1RepostSettingsId = (
    id: string,
    updateRepostSettingsRequest: UpdateRepostSettingsRequest,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/repost/settings/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateRepostSettingsRequest
    },
      );
    }
  


export const getPutApiV1RepostSettingsIdMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1RepostSettingsId>>, TError,{id: string;data: UpdateRepostSettingsRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiV1RepostSettingsId>>, TError,{id: string;data: UpdateRepostSettingsRequest}, TContext> => {

const mutationKey = ['putApiV1RepostSettingsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1RepostSettingsId>>, {id: string;data: UpdateRepostSettingsRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV1RepostSettingsId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV1RepostSettingsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1RepostSettingsId>>>
    export type PutApiV1RepostSettingsIdMutationBody = UpdateRepostSettingsRequest
    export type PutApiV1RepostSettingsIdMutationError = ProblemDetails

    /**
 * @summary Обновление настроек репоста (рандомность, активность).
 */
export const usePutApiV1RepostSettingsId = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1RepostSettingsId>>, TError,{id: string;data: UpdateRepostSettingsRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV1RepostSettingsId>>,
        TError,
        {id: string;data: UpdateRepostSettingsRequest},
        TContext
      > => {

      const mutationOptions = getPutApiV1RepostSettingsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Добавление целевого канала для репоста.
 */
export const postApiV1RepostSettingsSettingsIdDestinations = (
    settingsId: string,
    addRepostDestinationRequest: AddRepostDestinationRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<AddRepostDestinationResponse>(
      {url: `/api/v1/repost/settings/${settingsId}/destinations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addRepostDestinationRequest, signal
    },
      );
    }
  


export const getPostApiV1RepostSettingsSettingsIdDestinationsMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1RepostSettingsSettingsIdDestinations>>, TError,{settingsId: string;data: AddRepostDestinationRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1RepostSettingsSettingsIdDestinations>>, TError,{settingsId: string;data: AddRepostDestinationRequest}, TContext> => {

const mutationKey = ['postApiV1RepostSettingsSettingsIdDestinations'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1RepostSettingsSettingsIdDestinations>>, {settingsId: string;data: AddRepostDestinationRequest}> = (props) => {
          const {settingsId,data} = props ?? {};

          return  postApiV1RepostSettingsSettingsIdDestinations(settingsId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1RepostSettingsSettingsIdDestinationsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1RepostSettingsSettingsIdDestinations>>>
    export type PostApiV1RepostSettingsSettingsIdDestinationsMutationBody = AddRepostDestinationRequest
    export type PostApiV1RepostSettingsSettingsIdDestinationsMutationError = ProblemDetails

    /**
 * @summary Добавление целевого канала для репоста.
 */
export const usePostApiV1RepostSettingsSettingsIdDestinations = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1RepostSettingsSettingsIdDestinations>>, TError,{settingsId: string;data: AddRepostDestinationRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1RepostSettingsSettingsIdDestinations>>,
        TError,
        {settingsId: string;data: AddRepostDestinationRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1RepostSettingsSettingsIdDestinationsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Удаление целевого канала.
 */
export const deleteApiV1RepostDestinationsId = (
    id: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/repost/destinations/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiV1RepostDestinationsIdMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1RepostDestinationsId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1RepostDestinationsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV1RepostDestinationsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1RepostDestinationsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV1RepostDestinationsId(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1RepostDestinationsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1RepostDestinationsId>>>
    
    export type DeleteApiV1RepostDestinationsIdMutationError = ProblemDetails

    /**
 * @summary Удаление целевого канала.
 */
export const useDeleteApiV1RepostDestinationsId = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1RepostDestinationsId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1RepostDestinationsId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV1RepostDestinationsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Обновление статуса целевого канала (активен/неактивен).
 */
export const putApiV1RepostDestinationsId = (
    id: string,
    updateRepostDestinationRequest: UpdateRepostDestinationRequest,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/repost/destinations/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateRepostDestinationRequest
    },
      );
    }
  


export const getPutApiV1RepostDestinationsIdMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1RepostDestinationsId>>, TError,{id: string;data: UpdateRepostDestinationRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiV1RepostDestinationsId>>, TError,{id: string;data: UpdateRepostDestinationRequest}, TContext> => {

const mutationKey = ['putApiV1RepostDestinationsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1RepostDestinationsId>>, {id: string;data: UpdateRepostDestinationRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV1RepostDestinationsId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV1RepostDestinationsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1RepostDestinationsId>>>
    export type PutApiV1RepostDestinationsIdMutationBody = UpdateRepostDestinationRequest
    export type PutApiV1RepostDestinationsIdMutationError = ProblemDetails

    /**
 * @summary Обновление статуса целевого канала (активен/неактивен).
 */
export const usePutApiV1RepostDestinationsId = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1RepostDestinationsId>>, TError,{id: string;data: UpdateRepostDestinationRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV1RepostDestinationsId>>,
        TError,
        {id: string;data: UpdateRepostDestinationRequest},
        TContext
      > => {

      const mutationOptions = getPutApiV1RepostDestinationsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Обновление информации о целевом канале из Telegram.
 */
export const postApiV1RepostDestinationsIdRefresh = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/repost/destinations/${id}/refresh`, method: 'POST', signal
    },
      );
    }
  


export const getPostApiV1RepostDestinationsIdRefreshMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1RepostDestinationsIdRefresh>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1RepostDestinationsIdRefresh>>, TError,{id: string}, TContext> => {

const mutationKey = ['postApiV1RepostDestinationsIdRefresh'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1RepostDestinationsIdRefresh>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postApiV1RepostDestinationsIdRefresh(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1RepostDestinationsIdRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1RepostDestinationsIdRefresh>>>
    
    export type PostApiV1RepostDestinationsIdRefreshMutationError = ProblemDetails

    /**
 * @summary Обновление информации о целевом канале из Telegram.
 */
export const usePostApiV1RepostDestinationsIdRefresh = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1RepostDestinationsIdRefresh>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1RepostDestinationsIdRefresh>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPostApiV1RepostDestinationsIdRefreshMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    