/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * TgPoster.API
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DiscoverChannelResponsePagedResponse,
  DiscoverParseHistoryItemResponsePagedResponse,
  DiscoverStatsResponse,
  DiscoverStatusResponse,
  GetApiV1DiscoverParams,
  GetApiV1DiscoverParseHistoryParams,
  GetApiV1DiscoverStatsParams,
  ProblemDetails
} from '../tgPosterAPI.schemas';

import { customInstance } from '../../axios-instance';




/**
 * @summary Получить список обнаруженных каналов с пагинацией и фильтрацией
 */
export const getApiV1Discover = (
    params?: GetApiV1DiscoverParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<DiscoverChannelResponsePagedResponse>(
      {url: `/api/v1/discover`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiV1DiscoverQueryKey = (params?: GetApiV1DiscoverParams,) => {
    return [
    `/api/v1/discover`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV1DiscoverQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1Discover>>, TError = ProblemDetails>(params?: GetApiV1DiscoverParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Discover>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1DiscoverQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Discover>>> = ({ signal }) => getApiV1Discover(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1Discover>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1DiscoverQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Discover>>>
export type GetApiV1DiscoverQueryError = ProblemDetails


export function useGetApiV1Discover<TData = Awaited<ReturnType<typeof getApiV1Discover>>, TError = ProblemDetails>(
 params: undefined |  GetApiV1DiscoverParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Discover>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Discover>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Discover>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Discover<TData = Awaited<ReturnType<typeof getApiV1Discover>>, TError = ProblemDetails>(
 params?: GetApiV1DiscoverParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Discover>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Discover>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Discover>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Discover<TData = Awaited<ReturnType<typeof getApiV1Discover>>, TError = ProblemDetails>(
 params?: GetApiV1DiscoverParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Discover>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить список обнаруженных каналов с пагинацией и фильтрацией
 */

export function useGetApiV1Discover<TData = Awaited<ReturnType<typeof getApiV1Discover>>, TError = ProblemDetails>(
 params?: GetApiV1DiscoverParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Discover>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1DiscoverQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Получить список тематик обнаруженных каналов
 */
export const getApiV1DiscoverCategories = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<string[]>(
      {url: `/api/v1/discover/categories`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1DiscoverCategoriesQueryKey = () => {
    return [
    `/api/v1/discover/categories`
    ] as const;
    }

    
export const getGetApiV1DiscoverCategoriesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1DiscoverCategories>>, TError = ProblemDetails>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DiscoverCategories>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1DiscoverCategoriesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1DiscoverCategories>>> = ({ signal }) => getApiV1DiscoverCategories(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1DiscoverCategories>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1DiscoverCategoriesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1DiscoverCategories>>>
export type GetApiV1DiscoverCategoriesQueryError = ProblemDetails


export function useGetApiV1DiscoverCategories<TData = Awaited<ReturnType<typeof getApiV1DiscoverCategories>>, TError = ProblemDetails>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DiscoverCategories>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1DiscoverCategories>>,
          TError,
          Awaited<ReturnType<typeof getApiV1DiscoverCategories>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1DiscoverCategories<TData = Awaited<ReturnType<typeof getApiV1DiscoverCategories>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DiscoverCategories>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1DiscoverCategories>>,
          TError,
          Awaited<ReturnType<typeof getApiV1DiscoverCategories>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1DiscoverCategories<TData = Awaited<ReturnType<typeof getApiV1DiscoverCategories>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DiscoverCategories>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить список тематик обнаруженных каналов
 */

export function useGetApiV1DiscoverCategories<TData = Awaited<ReturnType<typeof getApiV1DiscoverCategories>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DiscoverCategories>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1DiscoverCategoriesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Получить состояние фоновой задачи обнаружения каналов
 */
export const getApiV1DiscoverStatus = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<DiscoverStatusResponse>(
      {url: `/api/v1/discover/status`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1DiscoverStatusQueryKey = () => {
    return [
    `/api/v1/discover/status`
    ] as const;
    }

    
export const getGetApiV1DiscoverStatusQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1DiscoverStatus>>, TError = ProblemDetails>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DiscoverStatus>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1DiscoverStatusQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1DiscoverStatus>>> = ({ signal }) => getApiV1DiscoverStatus(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1DiscoverStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1DiscoverStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1DiscoverStatus>>>
export type GetApiV1DiscoverStatusQueryError = ProblemDetails


export function useGetApiV1DiscoverStatus<TData = Awaited<ReturnType<typeof getApiV1DiscoverStatus>>, TError = ProblemDetails>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DiscoverStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1DiscoverStatus>>,
          TError,
          Awaited<ReturnType<typeof getApiV1DiscoverStatus>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1DiscoverStatus<TData = Awaited<ReturnType<typeof getApiV1DiscoverStatus>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DiscoverStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1DiscoverStatus>>,
          TError,
          Awaited<ReturnType<typeof getApiV1DiscoverStatus>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1DiscoverStatus<TData = Awaited<ReturnType<typeof getApiV1DiscoverStatus>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DiscoverStatus>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить состояние фоновой задачи обнаружения каналов
 */

export function useGetApiV1DiscoverStatus<TData = Awaited<ReturnType<typeof getApiV1DiscoverStatus>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DiscoverStatus>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1DiscoverStatusQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Получить статистику по обнаруженным каналам: итоги, свежесть, разбивки и таймлайны по дням
 */
export const getApiV1DiscoverStats = (
    params?: GetApiV1DiscoverStatsParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<DiscoverStatsResponse>(
      {url: `/api/v1/discover/stats`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiV1DiscoverStatsQueryKey = (params?: GetApiV1DiscoverStatsParams,) => {
    return [
    `/api/v1/discover/stats`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV1DiscoverStatsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1DiscoverStats>>, TError = ProblemDetails>(params?: GetApiV1DiscoverStatsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DiscoverStats>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1DiscoverStatsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1DiscoverStats>>> = ({ signal }) => getApiV1DiscoverStats(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1DiscoverStats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1DiscoverStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1DiscoverStats>>>
export type GetApiV1DiscoverStatsQueryError = ProblemDetails


export function useGetApiV1DiscoverStats<TData = Awaited<ReturnType<typeof getApiV1DiscoverStats>>, TError = ProblemDetails>(
 params: undefined |  GetApiV1DiscoverStatsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DiscoverStats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1DiscoverStats>>,
          TError,
          Awaited<ReturnType<typeof getApiV1DiscoverStats>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1DiscoverStats<TData = Awaited<ReturnType<typeof getApiV1DiscoverStats>>, TError = ProblemDetails>(
 params?: GetApiV1DiscoverStatsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DiscoverStats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1DiscoverStats>>,
          TError,
          Awaited<ReturnType<typeof getApiV1DiscoverStats>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1DiscoverStats<TData = Awaited<ReturnType<typeof getApiV1DiscoverStats>>, TError = ProblemDetails>(
 params?: GetApiV1DiscoverStatsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DiscoverStats>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить статистику по обнаруженным каналам: итоги, свежесть, разбивки и таймлайны по дням
 */

export function useGetApiV1DiscoverStats<TData = Awaited<ReturnType<typeof getApiV1DiscoverStats>>, TError = ProblemDetails>(
 params?: GetApiV1DiscoverStatsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DiscoverStats>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1DiscoverStatsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Получить историю парсинга: какие каналы и когда парсились, от самых свежих к старым
 */
export const getApiV1DiscoverParseHistory = (
    params?: GetApiV1DiscoverParseHistoryParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<DiscoverParseHistoryItemResponsePagedResponse>(
      {url: `/api/v1/discover/parse-history`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiV1DiscoverParseHistoryQueryKey = (params?: GetApiV1DiscoverParseHistoryParams,) => {
    return [
    `/api/v1/discover/parse-history`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV1DiscoverParseHistoryQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1DiscoverParseHistory>>, TError = ProblemDetails>(params?: GetApiV1DiscoverParseHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DiscoverParseHistory>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1DiscoverParseHistoryQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1DiscoverParseHistory>>> = ({ signal }) => getApiV1DiscoverParseHistory(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1DiscoverParseHistory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1DiscoverParseHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1DiscoverParseHistory>>>
export type GetApiV1DiscoverParseHistoryQueryError = ProblemDetails


export function useGetApiV1DiscoverParseHistory<TData = Awaited<ReturnType<typeof getApiV1DiscoverParseHistory>>, TError = ProblemDetails>(
 params: undefined |  GetApiV1DiscoverParseHistoryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DiscoverParseHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1DiscoverParseHistory>>,
          TError,
          Awaited<ReturnType<typeof getApiV1DiscoverParseHistory>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1DiscoverParseHistory<TData = Awaited<ReturnType<typeof getApiV1DiscoverParseHistory>>, TError = ProblemDetails>(
 params?: GetApiV1DiscoverParseHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DiscoverParseHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1DiscoverParseHistory>>,
          TError,
          Awaited<ReturnType<typeof getApiV1DiscoverParseHistory>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1DiscoverParseHistory<TData = Awaited<ReturnType<typeof getApiV1DiscoverParseHistory>>, TError = ProblemDetails>(
 params?: GetApiV1DiscoverParseHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DiscoverParseHistory>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить историю парсинга: какие каналы и когда парсились, от самых свежих к старым
 */

export function useGetApiV1DiscoverParseHistory<TData = Awaited<ReturnType<typeof getApiV1DiscoverParseHistory>>, TError = ProblemDetails>(
 params?: GetApiV1DiscoverParseHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DiscoverParseHistory>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1DiscoverParseHistoryQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




