/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * TgPoster.API
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DiscoverChannelResponsePagedResponse,
  GetApiV1DiscoverParams,
  ProblemDetails
} from '../tgPosterAPI.schemas';

import { customInstance } from '../../axios-instance';




/**
 * @summary Получить список обнаруженных каналов с пагинацией и фильтрацией
 */
export const getApiV1Discover = (
    params?: GetApiV1DiscoverParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<DiscoverChannelResponsePagedResponse>(
      {url: `/api/v1/discover`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiV1DiscoverQueryKey = (params?: GetApiV1DiscoverParams,) => {
    return [
    `/api/v1/discover`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV1DiscoverQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1Discover>>, TError = ProblemDetails>(params?: GetApiV1DiscoverParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Discover>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1DiscoverQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Discover>>> = ({ signal }) => getApiV1Discover(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1Discover>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1DiscoverQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Discover>>>
export type GetApiV1DiscoverQueryError = ProblemDetails


export function useGetApiV1Discover<TData = Awaited<ReturnType<typeof getApiV1Discover>>, TError = ProblemDetails>(
 params: undefined |  GetApiV1DiscoverParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Discover>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Discover>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Discover>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Discover<TData = Awaited<ReturnType<typeof getApiV1Discover>>, TError = ProblemDetails>(
 params?: GetApiV1DiscoverParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Discover>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Discover>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Discover>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Discover<TData = Awaited<ReturnType<typeof getApiV1Discover>>, TError = ProblemDetails>(
 params?: GetApiV1DiscoverParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Discover>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить список обнаруженных каналов с пагинацией и фильтрацией
 */

export function useGetApiV1Discover<TData = Awaited<ReturnType<typeof getApiV1Discover>>, TError = ProblemDetails>(
 params?: GetApiV1DiscoverParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Discover>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1DiscoverQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Получить список тематик обнаруженных каналов
 */
export const getApiV1DiscoverCategories = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<string[]>(
      {url: `/api/v1/discover/categories`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1DiscoverCategoriesQueryKey = () => {
    return [
    `/api/v1/discover/categories`
    ] as const;
    }

    
export const getGetApiV1DiscoverCategoriesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1DiscoverCategories>>, TError = ProblemDetails>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DiscoverCategories>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1DiscoverCategoriesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1DiscoverCategories>>> = ({ signal }) => getApiV1DiscoverCategories(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1DiscoverCategories>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1DiscoverCategoriesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1DiscoverCategories>>>
export type GetApiV1DiscoverCategoriesQueryError = ProblemDetails


export function useGetApiV1DiscoverCategories<TData = Awaited<ReturnType<typeof getApiV1DiscoverCategories>>, TError = ProblemDetails>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DiscoverCategories>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1DiscoverCategories>>,
          TError,
          Awaited<ReturnType<typeof getApiV1DiscoverCategories>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1DiscoverCategories<TData = Awaited<ReturnType<typeof getApiV1DiscoverCategories>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DiscoverCategories>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1DiscoverCategories>>,
          TError,
          Awaited<ReturnType<typeof getApiV1DiscoverCategories>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1DiscoverCategories<TData = Awaited<ReturnType<typeof getApiV1DiscoverCategories>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DiscoverCategories>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить список тематик обнаруженных каналов
 */

export function useGetApiV1DiscoverCategories<TData = Awaited<ReturnType<typeof getApiV1DiscoverCategories>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DiscoverCategories>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1DiscoverCategoriesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




