/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * TgPoster.API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ConnectBlueskyRequest,
  ConnectSocialAccountResponse,
  ProblemDetails,
  SocialAccountResponse
} from '../tgPosterAPI.schemas';

import { customInstance } from '../../axios-instance';




/**
 * @summary Получение списка аккаунтов соцсетей текущего пользователя
 */
export const getApiV1SocialAccounts = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<SocialAccountResponse[]>(
      {url: `/api/v1/social-accounts`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiV1SocialAccountsQueryKey = () => {
    return [
    `/api/v1/social-accounts`
    ] as const;
    }

    
export const getGetApiV1SocialAccountsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1SocialAccounts>>, TError = ProblemDetails>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SocialAccounts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1SocialAccountsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1SocialAccounts>>> = ({ signal }) => getApiV1SocialAccounts(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1SocialAccounts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1SocialAccountsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1SocialAccounts>>>
export type GetApiV1SocialAccountsQueryError = ProblemDetails


export function useGetApiV1SocialAccounts<TData = Awaited<ReturnType<typeof getApiV1SocialAccounts>>, TError = ProblemDetails>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SocialAccounts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SocialAccounts>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SocialAccounts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SocialAccounts<TData = Awaited<ReturnType<typeof getApiV1SocialAccounts>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SocialAccounts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SocialAccounts>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SocialAccounts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SocialAccounts<TData = Awaited<ReturnType<typeof getApiV1SocialAccounts>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SocialAccounts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получение списка аккаунтов соцсетей текущего пользователя
 */

export function useGetApiV1SocialAccounts<TData = Awaited<ReturnType<typeof getApiV1SocialAccounts>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SocialAccounts>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1SocialAccountsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Подключение аккаунта Bluesky
 */
export const postApiV1SocialAccountsBluesky = (
    connectBlueskyRequest: ConnectBlueskyRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ConnectSocialAccountResponse>(
      {url: `/api/v1/social-accounts/bluesky`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: connectBlueskyRequest, signal
    },
      );
    }
  


export const getPostApiV1SocialAccountsBlueskyMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SocialAccountsBluesky>>, TError,{data: ConnectBlueskyRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SocialAccountsBluesky>>, TError,{data: ConnectBlueskyRequest}, TContext> => {

const mutationKey = ['postApiV1SocialAccountsBluesky'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SocialAccountsBluesky>>, {data: ConnectBlueskyRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1SocialAccountsBluesky(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SocialAccountsBlueskyMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SocialAccountsBluesky>>>
    export type PostApiV1SocialAccountsBlueskyMutationBody = ConnectBlueskyRequest
    export type PostApiV1SocialAccountsBlueskyMutationError = ProblemDetails

    /**
 * @summary Подключение аккаунта Bluesky
 */
export const usePostApiV1SocialAccountsBluesky = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SocialAccountsBluesky>>, TError,{data: ConnectBlueskyRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SocialAccountsBluesky>>,
        TError,
        {data: ConnectBlueskyRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1SocialAccountsBlueskyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Удаление аккаунта соцсети
 */
export const deleteApiV1SocialAccountsId = (
    id: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/social-accounts/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiV1SocialAccountsIdMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1SocialAccountsId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1SocialAccountsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV1SocialAccountsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1SocialAccountsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV1SocialAccountsId(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1SocialAccountsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1SocialAccountsId>>>
    
    export type DeleteApiV1SocialAccountsIdMutationError = ProblemDetails

    /**
 * @summary Удаление аккаунта соцсети
 */
export const useDeleteApiV1SocialAccountsId = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1SocialAccountsId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1SocialAccountsId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV1SocialAccountsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    