name: Build and deploy for one server

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: [ self-hosted, runner ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build tgposter-api
        run: docker build -t tgposter-api:latest -f TgPoster.API/Dockerfile .

      - name: Build tgposter-worker
        run: docker build -t tgposter-worker:latest -f TgPoster.Worker/Dockerfile .

      - name: Build frontend
        run: docker build -t frontend:latest -f client/Dockerfile ./client

      - name: Create .env file
        run: |
          touch .env
          echo "TGPOSTER_API_IMAGE=tgposter-api:latest" >> .env
          echo "TGPOSTER_WORKER_IMAGE=tgposter-worker:latest" >> .env
          echo "TGPOSTER_FRONTEND_IMAGE=frontend:latest" >> .env
          echo "CONNECTIONSTRING=${{ secrets.CONNECTIONSTRING }}" >> .env
          echo "TGPOSTER_API_JWTOPTIONS_SECRETKEY=${{ secrets.JWTOPTIONS_SECRETKEY }}" >> .env
          echo "TELEGRAM_API_ID=${{ secrets.API_ID }}" >> .env
          echo "TELEGRAM_API_HASH=${{ secrets.API_HASH }}" >> .env
          echo "TELEGRAM_PHONE_NUMBER=${{ secrets.PHONE_NUMBER }}" >> .env
          echo "TELEGRAMOPTIONS_SECRETKEY=${{ secrets.TELEGRAMOPTIONS_SECRETKEY }}" >> .env
          echo "TELEGRAMOPTIONS_TELEGRAMSESSIONID=${{ secrets.TELEGRAMOPTIONS_TELEGRAMSESSIONID }}" >> .env
          echo "OPENROUTEROPTIONS_SECRETKEY=${{ secrets.OPENROUTEROPTIONS_SECRETKEY }}" >> .env
          echo "S3OPTIONS_ACESSKEY=${{ secrets.S3OPTIONS_ACESSKEY }}" >> .env
          echo "S3OPTIONS_SECRETKEY=${{ secrets.S3OPTIONS_SECRETKEY }}" >> .env
          echo "S3OPTIONS_SERVICEURL=${{ secrets.S3OPTIONS_SERVICEURL }}" >> .env
          echo "S3OPTIONS_BUCKETNAME=${{ secrets.S3OPTIONS_BUCKETNAME }}" >> .env

      - name: Restart containers
        run: |
          docker-compose -f docker/docker-compose.worker.yml -f docker/docker-compose.api.yml -f docker/docker-compose.frontend.yml up -d

      - name: Clean up old docker images and containers
        if: always()
        run: |
          docker container prune -f
          docker image prune -f

      - name: Remove .env file
        if: always()
        run: rm -f .env
